'use strict';
window.DaniAccountUI=(()=>{
 const q=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
 async function api(path,opts={}){const r=await fetch('/api/online'+path,{credentials:'same-origin',...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}
 function guest(){return JSON.parse(localStorage.getItem('ldb_prof')||'{"name":"Guest player","av":0}')}
 async function open(){modal('#mAccount');await refresh()}
 async function refresh(){const box=q('#accountBody');if(!box)return;box.innerHTML='<p class="hint">Loading account…</p>';if(!navigator.onLine){box.innerHTML='<p class="hint">Offline. Guest profile and offline games remain available.</p>';return}try{const me=await api('/auth?me=1');if(!me.user){box.innerHTML='<h3>Guest profile</h3><p>'+esc(guest().name||'Guest player')+'</p><p class="hint">Sign in from Online to use persistent friends, invitations and verified online history. Your guest profile is not overwritten automatically.</p>';return}const [p,h,f,i]=await Promise.all([api('/profile'),api('/history'),api('/friends'),api('/invitations')]);const prof=p.profile,st=p.stats;
 box.innerHTML='<section class="account-card"><h3>'+esc(prof.display_name)+'</h3><p><b>Player ID:</b> '+esc(prof.player_id)+'</p><p>'+st.gamesPlayed+' verified online games · '+st.wins+' wins · '+st.winRate+'% win rate</p><label>Display name<input id="accName" maxlength="24" value="'+esc(prof.display_name)+'"></label><label>Avatar<select id="accAvatar">'+[1,2,3,4,5].map(n=>'<option value="avatar-'+n+'" '+(prof.avatar==='avatar-'+n?'selected':'')+'>Avatar '+n+'</option>').join('')+'</select></label><button class="btn" data-acc="save">Save profile</button><button class="btn ghost" data-acc="migrate">Use my guest profile</button><p class="hint">Guest migration is explicit and changes only display name/avatar.</p></section>'+
 '<section class="account-card"><h3>Friends & requests</h3><div class="account-find"><input id="accPlayerId" placeholder="DL-PLAYERID"><button class="btn ghost" data-acc="add">Send request</button></div>'+(f.friends.length?f.friends.map(x=>'<div class="account-row"><span><b>'+esc(x.display_name)+'</b><small>'+esc(x.player_id||'')+' · '+esc(x.status)+'</small></span>'+(x.status==='pending'&&x.direction==='received'?'<button data-acc="accept" data-id="'+esc(x.player_id)+'">Accept</button><button data-acc="decline" data-id="'+esc(x.player_id)+'">Decline</button>':x.status==='pending'?'<button data-acc="cancel" data-id="'+esc(x.player_id)+'">Cancel</button>':'<button data-acc="remove" data-id="'+esc(x.player_id)+'">Remove</button>')+'<button data-acc="block" data-id="'+esc(x.player_id)+'">Block</button></div>').join(''):'<p class="hint">No friends or pending requests.</p>')+'</section>'+
 '<section class="account-card"><h3>Room invitations</h3>'+(i.invitations.length?i.invitations.map(x=>'<div class="account-row"><span><b>'+esc(x.sender?.display_name||'Player')+'</b><small>Invited you to a room</small></span><button data-acc="invite-accept" data-invite="'+x.id+'">Accept</button><button data-acc="invite-decline" data-invite="'+x.id+'">Decline</button></div>').join(''):'<p class="hint">No pending invitations.</p>')+'</section>'+
 '<section class="account-card"><h3>Verified online match history</h3>'+(h.history.length?h.history.map(x=>'<details><summary>'+esc(x.game)+' · '+esc(x.status)+' · '+new Date(x.completed_at).toLocaleString()+'</summary><p>'+x.participants.map(p=>esc(p.display_name)+(p.won?' — winner':'')).join(', ')+'</p></details>').join(''):'<p class="hint">No verified online matches yet. Offline results stay separate.</p>')+'</section>';
 }catch(e){box.innerHTML='<p class="err">'+esc(e.message)+'</p>'}}
 async function act(a,b){if(a==='save')await api('/profile',{method:'POST',body:JSON.stringify({displayName:q('#accName').value,avatar:q('#accAvatar').value})});else if(a==='migrate'){const g=guest();await api('/profile',{method:'POST',body:JSON.stringify({displayName:g.name,avatar:'avatar-'+((Number(g.av)||0)%5+1)})})}else if(a==='add')await api('/friends',{method:'POST',body:JSON.stringify({action:'send',playerId:q('#accPlayerId').value})});else if(['accept','decline','cancel','remove','block'].includes(a))await api('/friends',{method:'POST',body:JSON.stringify({action:a,playerId:b.dataset.id})});else if(a.startsWith('invite-')){const d=await api('/invitations',{method:'POST',body:JSON.stringify({action:a.slice(7),inviteId:b.dataset.invite})});if(d.code){modal('#mAccount',false);window.OnlinePlay?.open();setTimeout(()=>{const e=q('#onCode');if(e)e.value=d.code},100)}}await refresh()}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-acc]');if(b)act(b.dataset.acc,b).catch(x=>toast(x.message))});return{open,refresh};
})();