'use strict';
const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));
const COLORS=['red','green','yellow','blue'],NAMES={red:'Red',green:'Green',yellow:'Yellow',blue:'Blue'},HEX={red:'#e63946',green:'#2a9d5c',yellow:'#f4b400',blue:'#2f6fed'};
const PATH=[[6,1],[6,2],[6,3],[6,4],[6,5],[5,6],[4,6],[3,6],[2,6],[1,6],[0,6],[0,7],[0,8],[1,8],[2,8],[3,8],[4,8],[5,8],[6,9],[6,10],[6,11],[6,12],[6,13],[6,14],[7,14],[8,14],[8,13],[8,12],[8,11],[8,10],[8,9],[9,8],[10,8],[11,8],[12,8],[13,8],[14,8],[14,7],[14,6],[13,6],[12,6],[11,6],[10,6],[9,6],[8,5],[8,4],[8,3],[8,2],[8,1],[8,0],[7,0],[6,0]];
const COL={red:[[7,1],[7,2],[7,3],[7,4],[7,5]],green:[[1,7],[2,7],[3,7],[4,7],[5,7]],yellow:[[7,13],[7,12],[7,11],[7,10],[7,9]],blue:[[13,7],[12,7],[11,7],[10,7],[9,7]]};
const START={red:0,green:13,yellow:26,blue:39},SAFE=new Set([0,8,13,21,26,34,39,47]),BOFF={red:[0,0],green:[9,0],yellow:[9,9],blue:[0,9]},SLOT=[[2,2],[4,2],[2,4],[4,4]],STR={low:.5,med:1,high:2};
const Store={get(k,d){try{const v=JSON.parse(localStorage.getItem(k));return v??d}catch(e){return d}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}},del(k){try{localStorage.removeItem(k)}catch(e){}}};
const S=Object.assign({sound:1,music:0,vib:1,speed:1,stack:1},Store.get('ldb_set',{})),saveS=()=>Store.set('ldb_set',S);
const defCfg=()=>Object.fromEntries(COLORS.map(c=>[c,{mode:'normal',taps:5,strength:'med',status:'disabled',count:0,duration:'game',uses:0}]));
let CFG=Object.assign(defCfg(),Store.get('ldb_cfg',{}));const saveC=()=>Store.set('ldb_cfg',CFG);let LOG=Store.get('ldb_log',[]);
const log=m=>{LOG.unshift(new Date().toLocaleTimeString()+'  '+m);LOG.length=Math.min(LOG.length,40);Store.set('ldb_log',LOG)};
const Snd={ctx:null,mt:null,ac(){try{this.ctx=this.ctx||new(window.AudioContext||window.webkitAudioContext)();if(this.ctx.state==='suspended')this.ctx.resume();return this.ctx}catch(e){return null}},beep(f,d=.08,t='sine',v=.05,at=0){const c=this.ac();if(!c)return;try{const o=c.createOscillator(),g=c.createGain(),n=c.currentTime+at;o.type=t;o.frequency.value=f;g.gain.setValueAtTime(v,n);g.gain.exponentialRampToValueAtTime(.0001,n+d);o.connect(g);g.connect(c.destination);o.start(n);o.stop(n+d)}catch(e){}},seq(a,t='sine',d=.12,v=.05){a.forEach((f,i)=>this.beep(f,d,t,v,i*d*.8))},play(n){if(!S.sound)return;const m={roll:()=>this.seq([300,340,300,360],'square',.06,.03),move:()=>this.beep(520,.08,'sine',.05),cap:()=>this.seq([220,160,110],'sawtooth',.14,.05),home:()=>this.seq([660,880,1100],'triangle',.14,.05),win:()=>this.seq([523,659,784,1047,784,1047],'triangle',.18,.06),tap:()=>this.beep(420,.04,'sine',.04),six:()=>this.seq([784,988],'triangle',.1,.05)};m[n]&&m[n]()},music(on){clearInterval(this.mt);this.mt=null;if(!on||!S.music)return;const notes=[262,330,392,330,294,370,440,370],chords=[0,0,0,0,0,0,0,0];let i=0;this.mt=setInterval(()=>{if(document.hidden||!S.music)return;this.beep(notes[i%8]/2,.5,'sine',.018);if(i%4===0)this.beep(notes[i%8]/4,.9,'triangle',.02);i++},420)}};
const buzz=ms=>{if(S.vib&&navigator.vibrate)navigator.vibrate(ms)};
const Rules={dest(p,r){return p<0?((r===6||O.rules.leave==='any'||(O.rules.leave==='onesix'&&r===1))?0:null):p>=56?null:(p+r<=56?p+r:(O.rules.exact?null:56))},cell(c,p){return p>=0&&p<=50?(START[c]+p)%52:-1},legal(G,c,r){const o=[];G.pos[c].forEach((p,i)=>{if(this.dest(p,r)!==null)o.push(i)});return o},captures(G,c,np){const cl=this.cell(c,np);if(cl<0||SAFE.has(cl)||G.peace>0)return[];const out=[];for(const o of G.cols)if(o!==c){if(G.shield&&G.shield[o])continue;const here=[];G.pos[o].forEach((q,k)=>{if(this.cell(o,q)===cl)here.push([o,k])});if(S.stack&&here.length>=2)continue;out.push(...here)}return out},feats(G,c,r){const f={out:0,fin:0,cap:0,capn:0,safe:0,progress:0,danger:0};for(const i of this.legal(G,c,r)){const p=G.pos[c][i],np=this.dest(p,r),caps=this.captures(G,c,np);if(p<0)f.out=1;if(np===56)f.fin=1;if(caps.length){f.cap=1;f.capn=Math.max(f.capn,caps.length)}const cl=this.cell(c,np);if(np>50||(cl>=0&&SAFE.has(cl)))f.safe=1;f.progress=Math.max(f.progress,np<0?0:np/56);if(cl>=0&&!SAFE.has(cl)){for(const o of G.cols)if(o!==c)for(const q of G.pos[o]){if(q<0||q>50)continue;const oc=this.cell(o,q);if(oc<0)continue;const d=(cl-oc+52)%52;if(d>=1&&d<=6)f.danger=Math.max(f.danger,(7-d)/6)}}}return f}};
const MODES={good:{label:'Good Luck',w:(f,s)=>1+s*(1.5*f.out+2.2*f.fin+1.8*f.cap+.8*f.safe+.35*f.progress)},bad:{label:'Bad Luck',w:(f,s)=>1/(1+s*(1.35*f.out+1.9*f.fin+1.45*f.cap+.65*f.safe+.25*f.progress))},killer:{label:'Killer',w:(f,s)=>1+(f.cap?s*(7+2*f.capn):0)+s*.15*f.progress},defender:{label:'Defender',w:(f,s)=>1+s*(2.6*f.safe+1.2*f.out+1.4*f.fin+1.5*(1-f.danger))}};
const Dice={raw(){const a=new Uint8Array(1);do crypto.getRandomValues(a);while(a[0]>=252);return a[0]%6+1},roll(G,c){const cf=CFG[c],m=MODES[cf.mode];if(!m||cf.status!=='active')return this.raw();const s=STR[cf.strength]||1,w=[1,2,3,4,5,6].map(r=>Math.max(.35,m.w(Rules.feats(G,c,r),s)));let x=Math.random()*w.reduce((a,b)=>a+b,0);for(let r=0;r<6;r++){x-=w[r];if(x<=0)return r+1}return 6}};
const Modes={setMode(c,m){const f=CFG[c];f.mode=m;f.count=0;f.status=m==='normal'?'disabled':'waiting';saveC()},activate(c,manual){const f=CFG[c];if(f.mode==='normal')return;f.status='active';f.count=0;log(NAMES[c]+' mode activated'+(manual?' (manual)':''));saveC()},deactivate(c){const f=CFG[c];if(f.mode==='normal')return;f.status='disabled';log(NAMES[c]+' mode deactivated');saveC()},resetTaps(c){const f=CFG[c];f.count=0;if(f.mode!=='normal')f.status='waiting';saveC()},resetColor(c){CFG[c]=defCfg()[c];log(NAMES[c]+' reset');saveC()},armAll(){COLORS.forEach(c=>{if(CFG[c].mode!=='normal'){CFG[c].status='waiting';CFG[c].count=0}});saveC()}};
const Tap={timer:null,n:0,first:-1,color:null,SINGLE_WAIT:420,CHAIN_WAIT:900,handle(c,i){const f=CFG[c];if(f.mode==='normal'||f.status!=='waiting')return G_move(c,i);if(this.color&&this.color!==c)this.cancel();if(this.n===0){this.first=i;this.color=c}this.n++;f.count=this.n;saveC();clearTimeout(this.timer);if(this.n>=f.taps){this.n=0;this.first=-1;this.color=null;f.count=0;Modes.activate(c);buzz(45);saveC();return}const wait=this.n===1?this.SINGLE_WAIT:this.CHAIN_WAIT;this.timer=setTimeout(()=>{const n=this.n,k=this.first,col=this.color;this.n=0;this.first=-1;this.color=null;if(!col)return;CFG[col].count=0;saveC();if(n===1)G_move(col,k)},wait)},cancel(){clearTimeout(this.timer);if(this.color&&CFG[this.color]){CFG[this.color].count=0;saveC()}this.n=0;this.first=-1;this.color=null}};
let REPLAYING=false,G=null,busy=false,phase='roll';const T={};const newGame=n=>({cols:n===2?['red','yellow']:n===3?['red','green','yellow']:COLORS.slice(),pos:Object.fromEntries(COLORS.map(c=>[c,[-1,-1,-1,-1]])),turn:0,roll:null,sixes:0,ranks:[],bots:[],cards:{},shield:{},skip:null,peace:0,tc:0,rep:[],mx:{helper:{}}});const isBot=c=>!!(G&&G.bots&&G.bots.includes(c)),cur=()=>G.cols[G.turn],saveG=()=>{if(REPLAYING)return;G?Store.set('ldb_game',G):Store.del('ldb_game')};
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('on',s.id===id))}const modal=(id,on=true)=>$(id).classList.toggle('on',on);document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{b.closest('.modal').classList.remove('on');clearInterval(cpTimer);Snd.play('tap')});
function buildBoard(){const B=$('#board');B.innerHTML='';const add=(cls,l,t,txt)=>{const d=document.createElement('div');d.className=cls;d.style.left=l*100/15+'%';d.style.top=t*100/15+'%';if(txt)d.textContent=txt;B.appendChild(d);return d};COLORS.forEach(c=>{const[x,y]=BOFF[c],q=add('quad '+c,x,y);q.style.setProperty('--c',HEX[c]);add('qin',0,0).style.cssText='left:'+(x*100/15+40/6)+'%;top:'+(y*100/15+40/6)+'%;width:26.6%;height:26.6%'});B.appendChild(Object.assign(document.createElement('div'),{className:'ctr'}));PATH.forEach(([r,c],i)=>{const col=COLORS.find(k=>START[k]===i);add('cell '+(col||''),c,r,SAFE.has(i)?'★':'')});COLORS.forEach(c=>COL[c].forEach(([r,k])=>add('cell '+c,k,r)));Object.keys(T).forEach(k=>delete T[k]);G.cols.forEach(c=>G.pos[c].forEach((_,i)=>{const t=document.createElement('div');t.className='tok';t.style.setProperty('--c',HEX[c]);t.textContent=i+1;t.setAttribute('aria-label',NAMES[c]+' token '+(i+1));t.onclick=()=>onTok(c,i);B.appendChild(t);T[c+i]=t}))}
function xy(c,i,p){if(p<0){const[dx,dy]=BOFF[c],[sx,sy]=SLOT[i];return[dx+sx+.5,dy+sy+.5]}if(p<=50){const[r,k]=PATH[(START[c]+p)%52];return[k+.5,r+.5]}if(p<56){const[r,k]=COL[c][p-51];return[k+.5,r+.5]}const o={red:[-1,0],green:[0,-1],yellow:[1,0],blue:[0,1]}[c],d=(i-1.5)*.32;return[7.5+o[0]*.8+(o[1]?d:0),7.5+o[1]*.8+(o[0]?d:0)]}
function render(){if(!G)return;const can=(phase==='move'&&G.roll)?new Set(Rules.legal(G,cur(),G.roll)):new Set(),seen={};G.cols.forEach(c=>G.pos[c].forEach((p,i)=>{const[x,y]=xy(c,i,p),k=p>=0&&p<56?x+','+y:null,t=T[c+i];let dx=0;if(k){seen[k]=(seen[k]||0)+1;dx=(seen[k]-1)*.28}t.style.display=(G.variant==='quick'&&i>=2)?'none':'';t.style.left=(x+dx)*100/15+'%';t.style.top=y*100/15+'%';t.classList.toggle('can',c===cur()&&can.has(i))}));$('#bar').innerHTML=G.cols.map(c=>{const d=G.ranks.indexOf(c);return'<div class="chip '+(c===cur()&&!G.over?'act':'')+' '+(d>=0?'done':'')+'" style="--c:'+HEX[c]+'">'+(isBot(c)?'🤖 ':'')+NAMES[c]+(d>=0?' #'+(d+1):' '+(G.pos[c].filter(p=>p===56).length-(G.variant==='quick'?2:0))+'/'+(G.variant==='quick'?2:4))+badges(c)+(c===cur()&&!G.over?' ●':'')+'</div>'}).join('');face(phase==='pick'?0:(G.roll||1),!G.roll&&phase!=='pick');$('#bRoll').disabled=busy||phase!=='roll'||G.over||isBot(cur());$('#die').style.setProperty('--c',HEX[cur()]);$('#bRoll').style.setProperty('--c',HEX[cur()]);document.body.dataset.turn=cur();document.documentElement.style.setProperty('--sp',S.speed);if(typeof renderExtras==='function')renderExtras()}
const badges=c=>(G.mx&&G.mx.helper&&G.mx.helper[c]?' ✨':'')+(G.shield&&G.shield[c]?' 🛡':'')+(G.cards&&G.cards[c]&&G.cards[c].length?' 🃏'+G.cards[c].length:'');
const say=t=>$('#msg').textContent=t;
const PIPS=[[],[4],[0,8],[0,4,8],[0,2,6,8],[0,2,4,6,8],[0,2,3,5,6,8]];function face(n,dim){const d=$('#die');d.className=d.className.replace(/\bv\d\b/g,'').trim();d.classList.add('v'+n);d.classList.toggle('idle',!!dim);d.innerHTML=n===0?'<b class="star">★</b>':Array.from({length:9},(_,i)=>'<i'+(PIPS[n].includes(i)?' class="p"':'')+'></i>').join('');d.setAttribute('aria-label','Dice: '+n)}
function startGame(n,bots,variant){Snd.ac();Snd.music(1);Tap.cancel();G=newGame(n);if(bots)G.bots=G.cols.filter(c=>c!=='red');G.variant=variant||$('#sVar').value;if(G.variant==='quick')G.cols.forEach(c=>{G.pos[c][2]=56;G.pos[c][3]=56});if(G.variant==='rush')G.cols.forEach(c=>{G.pos[c]=[0,0,0,0]});Modes.armAll();initExtras();phase='roll';busy=false;buildBoard();saveG();show('game');say(NAMES[cur()]+' to roll');render();botTurn()}
function loadGame(){const g=Store.get('ldb_game',null);if(!g||!g.cols||!g.pos)return;Snd.ac();Snd.music(1);G=g;ensureExtras();Undo.h=[];busy=false;phase='roll';buildBoard();show('game');if(G.roll&&Rules.legal(G,cur(),G.roll).length){phase='move';say(NAMES[cur()]+': tap a glowing token')}else{G.roll=null;say(NAMES[cur()]+' to roll')}G.bots=G.bots||[];render();if(phase==='move'&&isBot(cur()))botPick();else botTurn()}
function doRoll(){return rollDice(false)}
function rollDice(again){if(busy||phase!=='roll'||G.over)return;busy=true;render();const d=$('#die');d.classList.add('roll');Snd.play('roll');return(async()=>{for(let k=0;k<6;k++){face(1+Math.floor(Math.random()*6));await sleep(80*S.speed)}d.classList.remove('roll');const c=cur(),r=Dice.roll(G,c);if(G.mx&&G.mx.chaos&&Math.random()<.125){busy=false;return wild(c)}return settle(c,r,again)})()}
async function settle(c,r,again){G.roll=r;if(r===6)Snd.play('six');face(r);G.sixes=r===6?G.sixes+1:0;if(O.rules.three6&&G.sixes>=3){say('Three 6s in a row - turn lost');busy=false;render();await sleep(900);return after(false)}const l=Rules.legal(G,c,r);busy=false;if(!l.length){say(NAMES[c]+' rolled '+r+' - no move');render();await sleep(900*S.speed);if(G.mx&&G.mx.helper&&G.mx.helper[c]&&!again&&!G.over){say(NAMES[c]+': helper re-roll');await sleep(500*S.speed);if(r===6)G.sixes--;G.roll=null;return rollDice(true)}return after(false)}phase='move';say(NAMES[c]+' rolled '+r+(isBot(c)?'':' - tap a glowing token'));saveG();render();if(isBot(c))botPick()}
function wild(c){G.roll=null;phase='pick';busy=false;Snd.play('six');say(NAMES[c]+' rolled a wild star - choose 1 to 6');render();if(isBot(c))setTimeout(()=>{if(G&&phase==='pick'&&cur()===c)pickVal(botWild(c))},800*S.speed)}
function pickVal(v){if(!G||phase!=='pick')return;busy=true;phase='roll';settle(cur(),v,false)}
function onTok(c,i){if(isBot(c)||busy||phase!=='move'||c!==cur()||!Rules.legal(G,c,G.roll).includes(i))return;Tap.handle(c,i)}
async function G_move(c,i){if(busy||phase!=='move')return;busy=true;phase='wait';const r=G.roll,old=G.pos[c][i],np=Rules.dest(old,r);if(np===null){busy=false;phase='move';return}Undo.push();render();if(old<0){G.pos[c][i]=0;Snd.play('move');render();await sleep(220*S.speed)}else for(let p=old+1;p<=np;p++){G.pos[c][i]=p;Snd.play('move');render();await sleep(140*S.speed)}let extra=r===6;const caps=Rules.captures(G,c,np);if(caps.length){Snd.play('cap');buzz(80);caps.forEach(([o,k])=>{T[o+k].classList.add('hit');G.pos[o][k]=-1});if(O.rules.capExtra)extra=true;captureCard(c);await sleep(350*S.speed);render();Object.values(T).forEach(t=>t.classList.remove('hit'))}if(np===56){Snd.play('home');extra=true}if(G.pos[c].every(p=>p===56)&&!G.ranks.includes(c)){G.ranks.push(c);say(NAMES[c]+' finished #'+G.ranks.length)}const left=G.cols.filter(x=>!G.ranks.includes(x));if(left.length<=1){if(left[0])G.ranks.push(left[0]);G.over=true;rec(c,r);saveG();render();return over()}rec(c,r);busy=false;after(extra)}
function after(extra){const c=cur();G.roll=null;if(G.ranks.includes(c))extra=false;if(!extra){G.sixes=0;const nx=()=>{do G.turn=(G.turn+1)%G.cols.length;while(G.ranks.includes(cur()))};nx();if(G.skip&&G.skip===cur()){toast(NAMES[cur()]+' skips a turn');G.skip=null;nx()}if(G.shield)delete G.shield[cur()];G.tc=(G.tc||0)+1;if(G.peace>0)G.peace--;hostTick()}phase='roll';busy=false;saveG();say(NAMES[cur()]+(extra?' rolls again':' to roll')+(G.peace>0?' - peace: no captures ('+G.peace+')':''));render();botTurn()}
const threat=(c,p)=>{const cl=Rules.cell(c,p);if(cl<0)return false;for(const o of G.cols)if(o!==c)for(const q of G.pos[o]){if(q<0||q>50)continue;const d=(cl-Rules.cell(o,q)+52)%52;if(d>=1&&d<=6)return true}return false};
function botBest(c,r){const l=Rules.legal(G,c,r),hard=O.diff==='hard';let best=null,bs=-1e9;l.forEach(i=>{const p=G.pos[c][i],np=Rules.dest(p,r),cl=Rules.cell(c,np);let sc=np/56*(hard?18:10);if(p<0)sc+=50;if(np===56)sc+=80;if(Rules.captures(G,c,np).length)sc+=100;if(np>50||(cl>=0&&SAFE.has(cl)))sc+=25;if(p>=0&&p<=50&&!SAFE.has(Rules.cell(c,p))&&threat(c,p))sc+=hard?45:30;if(cl>=0&&!SAFE.has(cl)&&threat(c,np))sc-=hard?55:35;sc+=Math.random();if(sc>bs){bs=sc;best=i}});return{i:best,s:bs,l}}
function botPick(){const c=cur(),r=G.roll,b=botBest(c,r);if(b.i===null)return;let i=b.i;if(O.diff==='easy'&&Math.random()<.6)i=b.l[Math.floor(Math.random()*b.l.length)];setTimeout(()=>{if(G&&!G.over&&cur()===c&&phase==='move'&&$('#game').classList.contains('on'))G_move(c,i)},650*S.speed)}
function botWild(c){let v=6,bs=-1e9;for(let x=1;x<=6;x++){const b=botBest(c,x);if(b.i!==null&&b.s>bs){bs=b.s;v=x}}return v}
function botTurn(){if(!G||G.over||!isBot(cur())||phase!=='roll')return;setTimeout(()=>{if(G&&!G.over&&isBot(cur())&&phase==='roll'&&!busy&&$('#game').classList.contains('on')){botCards(cur());doRoll()}},750*S.speed)}
$('#die').onclick=()=>{if(G&&!isBot(cur()))doRoll()};
const Stats={get:()=>Object.assign({games:0,wins:{}},Store.get('ldb_stats',{})),add(c){const st=this.get();st.games++;st.wins[c]=(st.wins[c]||0)+1;Store.set('ldb_stats',st)}};
function showStats(){const st=Stats.get(),el=$('#stats');el.textContent=st.games?st.games+' games played · '+Object.entries(st.wins).sort((a,b)=>b[1]-a[1]).map(([c,n])=>NAMES[c]+' '+n).join(' · '):''}
function confetti(){const box=$('#confetti');box.innerHTML='';for(let i=0;i<70;i++){const e=document.createElement('i');e.style.cssText='left:'+Math.random()*100+'%;background:'+HEX[COLORS[i%4]]+';animation-delay:'+Math.random()*.8+'s;animation-duration:'+(2+Math.random()*1.6)+'s;transform:rotate('+Math.random()*360+'deg)';box.appendChild(e)}box.classList.add('on');setTimeout(()=>box.classList.remove('on'),4200)}
function over(){Stats.add(G.ranks[0]);saveReplay();confetti();Snd.music(0);Snd.play('win');buzz(200);$('#ranks').innerHTML=G.ranks.map((c,i)=>'<li style="--c:'+HEX[c]+'"><span>'+(['🥇','🥈','🥉','4️⃣'][i]||'')+'</span><b>'+NAMES[c]+'</b></li>').join('');modal('#mOver');Store.del('ldb_game')}
function refreshHome(){showStats();$('#bCont').hidden=!Store.get('ldb_game',null)}document.querySelectorAll('[data-n]').forEach(b=>b.onclick=()=>{Snd.play('tap');startGame(+b.dataset.n,$('#sBots').checked)});$('#bCont').onclick=()=>{Snd.play('tap');loadGame()};$('#bRoll').onclick=doRoll;$('#bHow').onclick=()=>modal('#mRules');
const openSet=()=>{$('#sSound').checked=!!S.sound;$('#sMusic').checked=!!S.music;$('#sVib').checked=!!S.vib;$('#sStack').checked=!!S.stack;$('#sSpeed').value=String(S.speed);modal('#mSet')};$('#bSet').onclick=$('#bSet2').onclick=openSet;$('#sSound').onchange=e=>{S.sound=+e.target.checked;saveS()};$('#sMusic').onchange=e=>{S.music=+e.target.checked;saveS();Snd.music(G&&$('#game').classList.contains('on'))};$('#sStack').onchange=e=>{S.stack=+e.target.checked;saveS()};$('#sVib').onchange=e=>{S.vib=+e.target.checked;saveS()};$('#sSpeed').onchange=e=>{S.speed=+e.target.value;saveS();render()};$('#bMenu').onclick=()=>{REPLAYING=false;Snd.music(0);refreshHome();show('home')};$('#bRestart').onclick=()=>{if(G&&confirm('Restart this game?')){modal('#mSet',false);startGame(G.cols.length,G.bots&&G.bots.length,G.variant)}};$('#bRematch').onclick=()=>{modal('#mOver',false);startGame(G.cols.length,G.bots&&G.bots.length,G.variant)};$('#bHome').onclick=()=>{modal('#mOver',false);Snd.music(0);refreshHome();show('home')};
let defer=null;addEventListener('beforeinstallprompt',e=>{e.preventDefault();defer=e;$('#bInst').hidden=false});$('#bInst').onclick=async()=>{if(defer){defer.prompt();await defer.userChoice;defer=null;$('#bInst').hidden=true}};
let lt=[];function logoTap(){const n=Date.now();lt=lt.filter(t=>n-t<2000);lt.push(n);if(lt.length>=5){lt=[];$('#lerr').textContent='';$('#lp').value='';authUI();modal('#mLogin')}}$('#logo').onclick=$('#logo2').onclick=logoTap;
async function hash(s){try{const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}catch(e){let h=5381;for(const ch of s)h=(h*33^ch.charCodeAt(0))>>>0;return'x'+h}}
async function saveAuth(u,p){const salt=Math.random().toString(36).slice(2);Store.set('ldb_auth',{u,salt,h:await hash(salt+p)})}function authUI(){const exists=!!Store.get('ldb_auth',null);$('#loginTitle').textContent=exists?'DaniLabs access':'Create DaniLabs access';$('#loginHint').textContent=exists?'Private local control center':'First time only: choose your private local username and password.';$('#bLogin').textContent=exists?'Login':'Create access'}
$('#bLogin').onclick=async()=>{const u=$('#lu').value.trim(),p=$('#lp').value,a=Store.get('ldb_auth',null);if(!a){if(u.length<3||p.length<6){$('#lerr').textContent='Use at least 3 username characters and a 6 character password';return}await saveAuth(u,p);$('#lp').value='';modal('#mLogin',false);openCP();return}if(u===a.u&&await hash(a.salt+p)===a.h){$('#lp').value='';modal('#mLogin',false);openCP()}else{$('#lerr').textContent='Wrong username or password';$('#lp').value=''}};
let cpTimer=null;const PRE={fair:['Fair Game',()=>['normal',5]],lr:['Lucky Red',c=>c==='red'?['good',5]:['normal',5]],lg:['Lucky Green',c=>c==='green'?['good',5]:['normal',5]],ly:['Lucky Yellow',c=>c==='yellow'?['good',5]:['normal',5]],lb:['Lucky Blue',c=>c==='blue'?['good',5]:['normal',5]],chaos:['Chaos/Fun',()=>{const k=['normal',...Object.keys(MODES)];return[k[Math.floor(Math.random()*k.length)],4+Math.floor(Math.random()*7)]}],def:['Defensive Match',()=>['defender',6]],att:['Attack Match',()=>['killer',6]],custom:['Custom',null]};
const opts=(list,v,lab)=>list.map(x=>'<option value="'+x+'" '+(String(x)===String(v)?'selected':'')+'>'+(lab?lab(x):x)+'</option>').join('');
function statusText(c){const f=CFG[c];if(f.mode==='normal')return'Normal (no modification)';return'Configured: '+MODES[f.mode].label+' · Activation: '+f.taps+' taps · Current taps: '+f.count+'/'+f.taps+' · Status: '+(f.status==='waiting'?'Waiting':f.status==='active'?'Active':'Disabled')}
function renderCP(){$('#cpbody').innerHTML='<div class="pre">'+Object.entries(PRE).map(([k,v])=>'<button class="btn" data-p="'+k+'">'+v[0]+'</button>').join('')+'</div>'+COLORS.map(c=>{const f=CFG[c];return'<div class="card" style="--c:'+HEX[c]+'"><h3>'+NAMES[c]+'</h3><div class="g3"><label>Mode<select data-c="'+c+'" data-k="mode">'+opts(['normal',...Object.keys(MODES)],f.mode,k=>k==='normal'?'Normal':MODES[k].label)+'</select></label><label>Taps<select data-c="'+c+'" data-k="taps">'+opts([4,5,6,7,8,9,10],f.taps)+'</select></label><label>Strength<select data-c="'+c+'" data-k="strength">'+opts(['low','med','high'],f.strength,x=>({low:'Low',med:'Medium',high:'High'})[x])+'</select></label></div><p data-st="'+c+'"></p><div class="row"><button class="btn" data-a="on" data-c="'+c+'">Activate</button><button class="btn" data-a="off" data-c="'+c+'">Deactivate</button><button class="btn" data-a="rt" data-c="'+c+'">Reset taps</button><button class="btn" data-a="rc" data-c="'+c+'">Reset color</button></div></div>'}).join('')+'<button class="btn ghost" data-a="ra">Reset all colors</button><h3>Event log</h3><div id="logbox"></div><h3>Panel login</h3><input id="nu" placeholder="New username" autocomplete="off"><input id="np" type="password" placeholder="New password (min 6)" autocomplete="off"><button class="btn" data-a="cred">Save login</button><h3>Configuration</h3><textarea id="cfgjson" rows="4"></textarea><div class="row"><button class="btn" data-a="exp">Export JSON</button><button class="btn" data-a="imp">Import JSON</button></div><button class="btn ghost" data-a="wipe">Reset all stored data</button>';updCP()}
function updCP(){document.querySelectorAll('[data-st]').forEach(p=>p.textContent=statusText(p.dataset.st));const l=$('#logbox');if(l)l.innerHTML=LOG.map(x=>'<div>'+x+'</div>').join('')||'No events yet'}function openCP(){renderCP();modal('#mCP');clearInterval(cpTimer);cpTimer=setInterval(updCP,700)}
$('#cpbody').addEventListener('change',e=>{const t=e.target,c=t.dataset.c,k=t.dataset.k;if(!c)return;if(k==='mode'){Modes.setMode(c,t.value);log(NAMES[c]+' configured: '+(MODES[t.value]?.label||'Normal'))}else{CFG[c][k]=k==='taps'?+t.value:t.value;CFG[c].count=0;saveC()}updCP()});
$('#cpbody').addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const c=b.dataset.c,a=b.dataset.a;if(b.dataset.p){const p=PRE[b.dataset.p];if(p[1]){COLORS.forEach(x=>{const[m,t]=p[1](x);Modes.setMode(x,m);CFG[x].taps=t});saveC()}log('Preset: '+p[0]);return renderCP()}if(a==='on')Modes.activate(c,1);else if(a==='off')Modes.deactivate(c);else if(a==='rt')Modes.resetTaps(c);else if(a==='rc'){Modes.resetColor(c);renderCP()}else if(a==='ra'){COLORS.forEach(x=>Modes.resetColor(x));renderCP()}else if(a==='cred'){const u=$('#nu').value.trim(),p=$('#np').value;if(u&&p.length>=6){const salt=Math.random().toString(36).slice(2);Store.set('ldb_auth',{u,salt,h:await hash(salt+p)});$('#nu').value=$('#np').value='';log('Panel login changed')}}else if(a==='exp')$('#cfgjson').value=JSON.stringify(CFG,null,1);else if(a==='imp'){try{const o=JSON.parse($('#cfgjson').value);COLORS.forEach(x=>{if(o[x]&&(o[x].mode==='normal'||MODES[o[x].mode]))CFG[x]=Object.assign(defCfg()[x],{mode:o[x].mode,taps:Math.min(10,Math.max(4,+o[x].taps||5)),strength:STR[o[x].strength]?o[x].strength:'med',status:o[x].mode==='normal'?'disabled':'waiting'})});saveC();log('Config imported');renderCP()}catch(er){$('#cfgjson').value='Invalid JSON'}}else if(a==='wipe'&&confirm('Erase ALL stored data, including game and hidden settings?')){Object.keys(localStorage).filter(k=>k.startsWith('ldb_')).forEach(k=>localStorage.removeItem(k));location.reload()}updCP()});
refreshHome();face(1,true);
document.addEventListener('visibilitychange',()=>{if(document.hidden)Snd.ctx&&Snd.ctx.suspend&&Snd.ctx.suspend();else Snd.ctx&&Snd.ctx.resume&&Snd.ctx.resume()});
addEventListener('online',()=>toast('Back online'));addEventListener('offline',()=>toast('Offline mode - the game still works'));
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('on');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('on'),2200)}
addEventListener('appinstalled',()=>{$('#bInst').hidden=true;toast('Installed')});
if('serviceWorker'in navigator)addEventListener('load',()=>{const had=!!navigator.serviceWorker.controller;navigator.serviceWorker.register('sw.js').then(r=>{r.addEventListener('updatefound',()=>{const w=r.installing;w&&w.addEventListener('statechange',()=>{if(w.state==='installed'&&had)toast('Update ready - restart the app')})})}).catch(()=>{})});