'use strict';
const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));
const COLORS=['red','green','yellow','blue'],NAMES={red:'Red',green:'Green',yellow:'Yellow',blue:'Blue'},HEX={red:'#e63946',green:'#2a9d5c',yellow:'#f4b400',blue:'#2f6fed'};
const PATH=[[6,1],[6,2],[6,3],[6,4],[6,5],[5,6],[4,6],[3,6],[2,6],[1,6],[0,6],[0,7],[0,8],[1,8],[2,8],[3,8],[4,8],[5,8],[6,9],[6,10],[6,11],[6,12],[6,13],[6,14],[7,14],[8,14],[8,13],[8,12],[8,11],[8,10],[8,9],[9,8],[10,8],[11,8],[12,8],[13,8],[14,8],[14,7],[14,6],[13,6],[12,6],[11,6],[10,6],[9,6],[8,5],[8,4],[8,3],[8,2],[8,1],[8,0],[7,0],[6,0]];
const COL={red:[[7,1],[7,2],[7,3],[7,4],[7,5]],green:[[1,7],[2,7],[3,7],[4,7],[5,7]],yellow:[[7,13],[7,12],[7,11],[7,10],[7,9]],blue:[[13,7],[12,7],[11,7],[10,7],[9,7]]};
const START={red:0,green:13,yellow:26,blue:39},SAFE=new Set([0,8,13,21,26,34,39,47]),BOFF={red:[0,0],green:[9,0],yellow:[9,9],blue:[0,9]},SLOT=[[1.5,1.5],[3.5,1.5],[1.5,3.5],[3.5,3.5]];
const Store={get(k,d){try{const v=JSON.parse(localStorage.getItem(k));return v??d}catch(e){return d}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}},del(k){try{localStorage.removeItem(k)}catch(e){}}};
const S=Object.assign({sound:1,music:0,vib:1,speed:1,shake:0,instant:0},Store.get('ldb_set',{})),saveS=()=>Store.set('ldb_set',S);['sound','music','vib','shake','instant'].forEach(k=>S[k]=+!!S[k]);S.speed=[.5,1,1.6].includes(+S.speed)?+S.speed:1;
['ldb_cfg','ldb_secrets','ldb_cp_snapshot','ldb_cp_quick_taps','ldb_cp_follow','ldb_auth','ldb_log','ldb_theme'].forEach(k=>Store.del(k));
const Snd={ctx:null,mt:null,ac(){try{this.ctx=this.ctx||new(window.AudioContext||window.webkitAudioContext)();if(this.ctx.state==='suspended')this.ctx.resume();return this.ctx}catch(e){return null}},beep(f,d=.08,t='sine',v=.05,at=0){const c=this.ac();if(!c)return;try{const o=c.createOscillator(),g=c.createGain(),n=c.currentTime+at;o.type=t;o.frequency.value=f;g.gain.setValueAtTime(v,n);g.gain.exponentialRampToValueAtTime(.0001,n+d);o.connect(g);g.connect(c.destination);o.start(n);o.stop(n+d)}catch(e){}},seq(a,t='sine',d=.12,v=.05){a.forEach((f,i)=>this.beep(f,d,t,v,i*d*.8))},play(n){if(!S.sound)return;const m={roll:()=>this.seq([300,340,300,360],'square',.06,.03),move:()=>this.beep(520,.08,'sine',.05),cap:()=>this.seq([220,160,110],'sawtooth',.14,.05),home:()=>this.seq([660,880,1100],'triangle',.14,.05),win:()=>this.seq([523,659,784,1047,784,1047],'triangle',.18,.06),tap:()=>this.beep(420,.04,'sine',.04),six:()=>this.seq([784,988],'triangle',.1,.05)};m[n]&&m[n]()},music(on){clearInterval(this.mt);this.mt=null;if(!on||!S.music)return;const notes=[262,330,392,330,294,370,440,370],chords=[0,0,0,0,0,0,0,0];let i=0;this.mt=setInterval(()=>{if(document.hidden||!S.music)return;this.beep(notes[i%8]/2,.5,'sine',.018);if(i%4===0)this.beep(notes[i%8]/4,.9,'triangle',.02);i++},420)}};
const buzz=ms=>{if(S.vib&&navigator.vibrate)navigator.vibrate(ms)};
const Rules={
 dest(p,r){return p<0?(r===6?0:null):p>=56?null:(p+r<=56?p+r:null)},
 cell(c,p){return p>=0&&p<=50?(START[c]+p)%52:-1},
 legal(G,c,r){const o=[];G.pos[c].forEach((p,i)=>{if(this.dest(p,r)!==null)o.push(i)});return o},
 captures(G,c,np){const cl=this.cell(c,np);if(cl<0||SAFE.has(cl))return[];const out=[];for(const o of G.cols)if(o!==c){const here=[];G.pos[o].forEach((q,k)=>{if(this.cell(o,q)===cl)here.push([o,k])});if(here.length>=2)continue;out.push(...here)}return out},
 feats(G,c,r){const f={out:0,fin:0,cap:0,capn:0,safe:0,progress:0,danger:0};for(const i of this.legal(G,c,r)){const p=G.pos[c][i],np=this.dest(p,r),caps=this.captures(G,c,np);if(p<0)f.out=1;if(np===56)f.fin=1;if(caps.length){f.cap=1;f.capn=Math.max(f.capn,caps.length)}const cl=this.cell(c,np);if(np>50||(cl>=0&&SAFE.has(cl)))f.safe=1;f.progress=Math.max(f.progress,np<0?0:np/56);if(cl>=0&&!SAFE.has(cl)){for(const o of G.cols)if(o!==c)for(const q of G.pos[o]){if(q<0||q>50)continue;const oc=this.cell(o,q);if(oc<0)continue;const d=(cl-oc+52)%52;if(d>=1&&d<=6)f.danger=Math.max(f.danger,(7-d)/6)}}}return f}
};
const Dice={raw(){const a=new Uint8Array(1);do crypto.getRandomValues(a);while(a[0]>=252);return a[0]%6+1},roll(){return this.raw()}};
let REPLAYING=false,G=null,busy=false,phase='roll';const T={};const newGame=n=>({cols:n===2?['red','yellow']:n===3?['red','green','yellow']:COLORS.slice(),pos:Object.fromEntries(COLORS.map(c=>[c,[-1,-1,-1,-1]])),turn:0,roll:null,sixes:0,ranks:[],bots:[],rep:[]});const isBot=c=>!!(G&&G.bots&&G.bots.includes(c)),cur=()=>G.cols[G.turn],saveG=()=>{if(REPLAYING)return;if(G&&G.online){return}G?Store.set('ldb_game',G):Store.del('ldb_game')};
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('on',s.id===id))}const modal=(id,on=true)=>$(id).classList.toggle('on',on);document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{b.closest('.modal').classList.remove('on');Snd.play('tap')});
function buildBoard(){const B=$('#board');B.innerHTML='';const add=(cls,l,t,txt)=>{const d=document.createElement('div');d.className=cls;d.style.left=l*100/15+'%';d.style.top=t*100/15+'%';if(txt)d.textContent=txt;B.appendChild(d);return d};COLORS.forEach(c=>{const[x,y]=BOFF[c],q=add('quad '+c,x,y);q.style.setProperty('--c',HEX[c]);add('qin',0,0).style.cssText='left:'+(x*100/15+40/6)+'%;top:'+(y*100/15+40/6)+'%;width:26.6%;height:26.6%'});B.appendChild(Object.assign(document.createElement('div'),{className:'ctr'}));PATH.forEach(([r,c],i)=>{const col=COLORS.find(k=>START[k]===i);add('cell '+(col||''),c,r,SAFE.has(i)?'★':'')});COLORS.forEach(c=>COL[c].forEach(([r,k])=>add('cell '+c,k,r)));Object.keys(T).forEach(k=>delete T[k]);G.cols.forEach(c=>G.pos[c].forEach((_,i)=>{const t=document.createElement('div');t.className='tok';t.style.setProperty('--c',HEX[c]);t.textContent=i+1;t.setAttribute('aria-label',NAMES[c]+' token '+(i+1));t.onclick=()=>onTok(c,i);B.appendChild(t);T[c+i]=t}))}
function xy(c,i,p){if(p<0){const[dx,dy]=BOFF[c],[sx,sy]=SLOT[i];return[dx+sx+.5,dy+sy+.5]}if(p<=50){const[r,k]=PATH[(START[c]+p)%52];return[k+.5,r+.5]}if(p<56){const[r,k]=COL[c][p-51];return[k+.5,r+.5]}const o={red:[-1,0],green:[0,-1],yellow:[1,0],blue:[0,1]}[c],d=(i-1.5)*.32;return[7.5+o[0]*.8+(o[1]?d:0),7.5+o[1]*.8+(o[0]?d:0)]}
function render(){if(!G)return;const mine=!G.online||!window.OnlinePlay||OnlinePlay.myColor()===cur(),can=(mine&&phase==='move'&&G.roll)?new Set(Rules.legal(G,cur(),G.roll)):new Set(),seen={};G.cols.forEach(c=>G.pos[c].forEach((p,i)=>{const[x,y]=xy(c,i,p),k=p>=0&&p<56?x+','+y:null,t=T[c+i];let dx=0;if(k){seen[k]=(seen[k]||0)+1;dx=(seen[k]-1)*.28}t.style.display=(G.variant==='quick'&&i>=2)?'none':'';t.style.left=(x+dx)*100/15+'%';t.style.top=y*100/15+'%';t.classList.toggle('can',c===cur()&&can.has(i))}));$('#bar').innerHTML=G.cols.map(c=>{const d=G.ranks.indexOf(c);return'<div class="chip '+(c===cur()&&!G.over?'act':'')+' '+(d>=0?'done':'')+'" style="--c:'+HEX[c]+'">'+(isBot(c)?'🤖 ':'')+NAMES[c]+(d>=0?' #'+(d+1):' '+(G.pos[c].filter(p=>p===56).length-(G.variant==='quick'?2:0))+'/'+(G.variant==='quick'?2:4))+badges(c)+(c===cur()&&!G.over?' ●':'')+'</div>'}).join('');face(phase==='pick'?0:(G.roll||1),!G.roll&&phase!=='pick');$('#bRoll').disabled=busy||phase!=='roll'||G.over||isBot(cur())||!mine;$('#die').style.setProperty('--c',HEX[cur()]);$('#bRoll').style.setProperty('--c',HEX[cur()]);document.body.dataset.turn=cur();document.documentElement.style.setProperty('--sp',S.speed);if(typeof renderExtras==='function')renderExtras()}
const badges=()=>'';
const say=t=>$('#msg').textContent=t;
const PIPS=[[],[4],[0,8],[0,4,8],[0,2,6,8],[0,2,4,6,8],[0,2,3,5,6,8]];function face(n,dim){const d=$('#die');d.className=d.className.replace(/\bv\d\b/g,'').trim();d.classList.add('v'+n);d.classList.toggle('idle',!!dim);d.innerHTML=n===0?'<b class="star">★</b>':Array.from({length:9},(_,i)=>'<i'+(PIPS[n].includes(i)?' class="p"':'')+'></i>').join('');d.setAttribute('aria-label','Dice: '+n)}
function startGame(n,bots,variant){if(window.OnlinePlay&&OnlinePlay.prepareLocal)OnlinePlay.prepareLocal();Snd.ac();Snd.music(1);if($('#bRematch'))$('#bRematch').hidden=false;G=newGame(n);if(bots)G.bots=G.cols.filter(c=>c!=='red');const v=variant||$('#sVar').value;G.variant=['classic','quick','rush'].includes(v)?v:'classic';if(G.variant==='quick')G.cols.forEach(c=>{G.pos[c][2]=56;G.pos[c][3]=56});if(G.variant==='rush')G.cols.forEach(c=>{G.pos[c]=[0,0,0,0]});initExtras();phase='roll';busy=false;buildBoard();saveG();show('game');say(NAMES[cur()]+' to roll');render();botTurn()}
function normalizeSavedGame(g){if(!g||!Array.isArray(g.cols)||g.cols.length<2||g.cols.length>4||new Set(g.cols).size!==g.cols.length||g.cols.some(c=>!COLORS.includes(c))||!g.pos||typeof g.pos!=='object')return null;const pos={};COLORS.forEach(c=>{const a=Array.isArray(g.pos[c])?g.pos[c]:[];pos[c]=Array.from({length:4},(_,i)=>{const p=Number(a[i]);return Number.isInteger(p)&&p>=-1&&p<=56?p:-1})});g.pos=pos;g.turn=Math.max(0,Math.min(g.cols.length-1,Math.floor(+g.turn||0)));g.ranks=Array.isArray(g.ranks)?[...new Set(g.ranks)].filter(c=>g.cols.includes(c)):[];g.roll=[1,2,3,4,5,6].includes(+g.roll)?+g.roll:null;g.sixes=Math.max(0,Math.min(2,Math.floor(+g.sixes||0)));g.variant=['classic','quick','rush'].includes(g.variant)?g.variant:'classic';if(g.over)return null;return g}
function loadGame(){const g=normalizeSavedGame(Store.get('ldb_game',null));if(!g){Store.del('ldb_game');refreshHome();toast('Saved game could not be loaded');return}Snd.ac();Snd.music(1);G=g;ensureExtras();busy=false;phase='roll';buildBoard();show('game');if(G.roll&&Rules.legal(G,cur(),G.roll).length){phase='move';say(NAMES[cur()]+': tap a glowing token')}else{G.roll=null;say(NAMES[cur()]+' to roll')}render();if(phase==='move'&&isBot(cur()))botPick();else botTurn()}
function doRoll(){if(G&&G.online&&window.OnlinePlay)return OnlinePlay.requestRoll();return rollDice(false)}
function rollDice(){if(!G||busy||phase!=='roll'||G.over)return;busy=true;render();const d=$('#die');d.classList.add('roll');Snd.play('roll');return(async()=>{const spins=S.instant?1:6,delay=S.instant?35:80*S.speed;for(let k=0;k<spins;k++){face(1+Math.floor(Math.random()*6));await sleep(delay)}d.classList.remove('roll');const c=cur(),r=Dice.roll();return settle(c,r)})()}
async function settle(c,r){G.roll=r;if(r===6)Snd.play('six');face(r);G.sixes=r===6?G.sixes+1:0;if(G.sixes>=3){say('Three 6s in a row - turn lost');busy=false;render();await sleep(900);return after(false)}const l=Rules.legal(G,c,r);busy=false;if(!l.length){say(NAMES[c]+' rolled '+r+' - no move');render();await sleep(900*S.speed);if(!G||G.over||cur()!==c||G.roll!==r)return;return after(false)}phase='move';say(NAMES[c]+' rolled '+r+(isBot(c)?'':' - tap a glowing token'));saveG();render();if(isBot(c))botPick()}
function onTok(c,i){if(!G)return;if(G.online&&window.OnlinePlay)return OnlinePlay.requestMove(c,i);if(busy||isBot(c)||phase!=='move'||c!==cur()||!Rules.legal(G,c,G.roll).includes(i))return;G_move(c,i)}
async function G_move(c,i){if(busy||phase!=='move')return;busy=true;phase='wait';const r=G.roll,old=G.pos[c][i],np=Rules.dest(old,r);if(np===null){busy=false;phase='move';return}render();if(old<0){G.pos[c][i]=0;Snd.play('move');render();await sleep(220*S.speed)}else for(let p=old+1;p<=np;p++){G.pos[c][i]=p;Snd.play('move');render();await sleep(140*S.speed)}let extra=r===6;const caps=Rules.captures(G,c,np);if(caps.length){Snd.play('cap');buzz(80);caps.forEach(([o,k])=>{T[o+k].classList.add('hit');G.pos[o][k]=-1});extra=true;await sleep(350*S.speed);render();Object.values(T).forEach(t=>t.classList.remove('hit'))}if(np===56){Snd.play('home');extra=true}if(G.pos[c].every(p=>p===56)&&!G.ranks.includes(c)){G.ranks.push(c);say(NAMES[c]+' finished #'+G.ranks.length)}const left=G.cols.filter(x=>!G.ranks.includes(x));if(left.length<=1){if(left[0])G.ranks.push(left[0]);G.over=true;rec(c,r);saveG();render();return over()}rec(c,r);busy=false;after(extra)}
function after(extra){const c=cur();G.roll=null;if(G.ranks.includes(c))extra=false;if(!extra){G.sixes=0;const nx=()=>{do G.turn=(G.turn+1)%G.cols.length;while(G.ranks.includes(cur()))};nx()}phase='roll';busy=false;saveG();say(NAMES[cur()]+(extra?' rolls again':' to roll'));render();botTurn()}
const threat=(c,p)=>{const cl=Rules.cell(c,p);if(cl<0)return false;for(const o of G.cols)if(o!==c)for(const q of G.pos[o]){if(q<0||q>50)continue;const d=(cl-Rules.cell(o,q)+52)%52;if(d>=1&&d<=6)return true}return false};
function botBest(c,r){const l=Rules.legal(G,c,r),hard=O.diff==='hard';let best=null,bs=-1e9;l.forEach(i=>{const p=G.pos[c][i],np=Rules.dest(p,r),cl=Rules.cell(c,np);let sc=np/56*(hard?18:10);if(p<0)sc+=50;if(np===56)sc+=80;if(Rules.captures(G,c,np).length)sc+=100;if(np>50||(cl>=0&&SAFE.has(cl)))sc+=25;if(p>=0&&p<=50&&!SAFE.has(Rules.cell(c,p))&&threat(c,p))sc+=hard?45:30;if(cl>=0&&!SAFE.has(cl)&&threat(c,np))sc-=hard?55:35;sc+=Math.random();if(sc>bs){bs=sc;best=i}});return{i:best,s:bs,l}}
function botPick(){const c=cur(),r=G.roll,b=botBest(c,r);if(b.i===null)return;let i=b.i;if(O.diff==='easy'&&Math.random()<.6)i=b.l[Math.floor(Math.random()*b.l.length)];setTimeout(()=>{if(G&&!G.over&&cur()===c&&phase==='move'&&$('#game').classList.contains('on'))G_move(c,i)},650*S.speed)}
function botTurn(){if(!G||G.over||!isBot(cur())||phase!=='roll')return;setTimeout(()=>{if(G&&!G.over&&isBot(cur())&&phase==='roll'&&!busy&&$('#game').classList.contains('on'))doRoll()},750*S.speed)}
$('#die').onclick=()=>{if(G&&!isBot(cur()))doRoll()};
const Stats={get:()=>Object.assign({games:0,wins:{}},Store.get('ldb_stats',{})),add(c){const st=this.get();st.games++;st.wins[c]=(st.wins[c]||0)+1;Store.set('ldb_stats',st)}};
function showStats(){const st=Stats.get(),el=$('#stats');el.textContent=st.games?st.games+' games played · '+Object.entries(st.wins).sort((a,b)=>b[1]-a[1]).map(([c,n])=>NAMES[c]+' '+n).join(' · '):''}
function confetti(){const box=$('#confetti');box.innerHTML='';for(let i=0;i<70;i++){const e=document.createElement('i');e.style.cssText='left:'+Math.random()*100+'%;background:'+HEX[COLORS[i%4]]+';animation-delay:'+Math.random()*.8+'s;animation-duration:'+(2+Math.random()*1.6)+'s;transform:rotate('+Math.random()*360+'deg)';box.appendChild(e)}box.classList.add('on');setTimeout(()=>box.classList.remove('on'),4200)}
function over(){Stats.add(G.ranks[0]);saveReplay();confetti();Snd.music(0);Snd.play('win');buzz(200);$('#ranks').innerHTML=G.ranks.map((c,i)=>'<li style="--c:'+HEX[c]+'"><span>'+(['🥇','🥈','🥉','4️⃣'][i]||'')+'</span><b>'+NAMES[c]+'</b></li>').join('');modal('#mOver');Store.del('ldb_game')}
function refreshHome(){showStats();$('#bCont').hidden=!Store.get('ldb_game',null)}document.querySelectorAll('[data-n]').forEach(b=>b.onclick=()=>{Snd.play('tap');startGame(+b.dataset.n,$('#sBots').checked)});$('#bCont').onclick=()=>{Snd.play('tap');loadGame()};$('#bRoll').onclick=doRoll;$('#bHow').onclick=()=>modal('#mRules');
const motionSupported=()=>typeof DeviceMotionEvent!=='undefined';
const diceAnimValue=()=>S.instant?'instant':S.speed===.5?'fast':S.speed===1.6?'relaxed':'normal';
const openSet=()=>{$('#sSound').checked=!!S.sound;$('#sMusic').checked=!!S.music;$('#sVib').checked=!!S.vib;$('#sShake').checked=!!S.shake;$('#sShake').disabled=!motionSupported();$('#sDiceAnim').value=diceAnimValue();$('#bRestart').hidden=!(G&&!G.over&&!G.online&&$('#game').classList.contains('on'));$('#shakeHint').textContent=motionSupported()?'Uses your device motion sensor only while a match is open.':'Shake to Roll is not available on this device/browser.';modal('#mSet')};
$('#bSet').onclick=$('#bSet2').onclick=openSet;const nSettings=$('#nSettings');if(nSettings)nSettings.onclick=openSet;
$('#sSound').onchange=e=>{S.sound=+e.target.checked;saveS()};
$('#sMusic').onchange=e=>{S.music=+e.target.checked;saveS();Snd.music(G&&$('#game').classList.contains('on'))};
$('#sVib').onchange=e=>{S.vib=+e.target.checked;saveS()};
$('#sShake').onchange=async e=>{if(!e.target.checked){S.shake=0;saveS();return}if(!motionSupported()){e.target.checked=false;S.shake=0;saveS();toast('Shake to Roll is not supported here');return}try{if(typeof DeviceMotionEvent.requestPermission==='function'){const p=await DeviceMotionEvent.requestPermission();if(p!=='granted')throw new Error('denied')}S.shake=1;saveS();toast('Shake to Roll enabled')}catch(err){e.target.checked=false;S.shake=0;saveS();toast('Motion permission was not enabled')}};
$('#sDiceAnim').onchange=e=>{const v=e.target.value;S.instant=+(v==='instant');S.speed=v==='fast'?.5:v==='relaxed'?1.6:1;saveS();if(G)render()};
$('#bMenu').onclick=()=>{if(G&&G.online&&window.OnlinePlay){OnlinePlay.leave();return}REPLAYING=false;Snd.music(0);refreshHome();show('home')};$('#bRestart').onclick=()=>{if(G&&!G.online&&confirm('Restart this game?')){modal('#mSet',false);startGame(G.cols.length,G.bots&&G.bots.length,G.variant)}};$('#bRematch').onclick=()=>{modal('#mOver',false);startGame(G.cols.length,G.bots&&G.bots.length,G.variant)};$('#bHome').onclick=()=>{modal('#mOver',false);Snd.music(0);refreshHome();show('home')};
let shakeLast=0,shakeMag=0;addEventListener('devicemotion',e=>{if(!S.shake||!G||G.over||busy||phase!=='roll'||isBot(cur())||!$('#game').classList.contains('on'))return;const a=e.accelerationIncludingGravity||e.acceleration;if(!a)return;const mag=Math.hypot(+a.x||0,+a.y||0,+a.z||0),now=Date.now(),delta=Math.abs(mag-shakeMag);shakeMag=mag;if(delta>12&&now-shakeLast>1200){shakeLast=now;buzz(35);doRoll()}},{passive:true});
let defer=null;addEventListener('beforeinstallprompt',e=>{e.preventDefault();defer=e;$('#bInst').hidden=false});$('#bInst').onclick=async()=>{if(defer){defer.prompt();await defer.userChoice;defer=null;$('#bInst').hidden=true}};
async function hash(s){try{const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}catch(e){let h=5381;for(const ch of s)h=(h*33^ch.charCodeAt(0))>>>0;return'x'+h}}
refreshHome();face(1,true);
document.addEventListener('visibilitychange',()=>{if(document.hidden){Snd.ctx&&Snd.ctx.suspend&&Snd.ctx.suspend()}else Snd.ctx&&Snd.ctx.resume&&Snd.ctx.resume()});
addEventListener('online',()=>toast('Back online'));addEventListener('offline',()=>toast('Offline mode - the game still works'));
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('on');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('on'),2200)}
addEventListener('appinstalled',()=>{$('#bInst').hidden=true;toast('Installed')});
if('serviceWorker'in navigator)addEventListener('load',()=>{const had=!!navigator.serviceWorker.controller;let refreshing=false;if(had)navigator.serviceWorker.addEventListener('controllerchange',()=>{if(refreshing)return;refreshing=true;location.reload()});navigator.serviceWorker.register('sw.js').then(r=>{r.addEventListener('updatefound',()=>{const w=r.installing;w&&w.addEventListener('statechange',()=>{if(w.state==='installed'&&had)toast('Updating app…')})})}).catch(()=>{})});
