'use strict';
/* DaniLabs Online v42 — same-origin sessions + server-authoritative Ludo and Color Cards. */
(function(){
const API='/api/online';
let user=null,room=null,members=[],deadlineTimer=null,presenceTimer=null,statusTimer=null,busyNet=false,connectionState='Disconnected',lastVersion=-1,lastRoomStatus='',startedRoom='',authMode='login',recoveryShown='',serviceError='',savedNames=null;
const q=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const signed=()=>!!user,uid=()=>user&&user.id,username=()=>user&&user.username||'Player';
const notice=(m,bad=false)=>{const e=q('#onlineMsg');if(!e)return;e.textContent=m||'';e.classList.toggle('err',!!bad)};
async function call(path,opts={}){const r=await fetch(API+path,Object.assign({credentials:'same-origin'},opts,{headers:Object.assign({'Content-Type':'application/json'},opts.headers||{})}));let data=null;try{data=await r.json()}catch(e){}if(!r.ok)throw new Error((data&&data.error)||('Request failed '+r.status));return data}
async function checkInvites(){if(!signed()||!navigator.onLine)return;try{const d=await call('/invitations');if(d.invitations?.length){const n=q('#bNotify');if(n){n.dataset.count=String(d.invitations.length);n.setAttribute('aria-label',d.invitations.length+' room invitations')}}}catch(e){}}
function profileState(){const el=q('#pName')&&q('#pName').nextElementSibling;if(!el)return;el.innerHTML=signed()?'<i></i> ONLINE · @'+esc(username()):'<i></i> OFFLINE'}
function authHTML(){
 if(recoveryShown)return '<div class="online-recovery"><div class="online-mark">✓</div><h3>Save your recovery code</h3><p>This code can reset your password if you forget it. Keep it private and save it somewhere safe. It is shown only now.</p><code>'+esc(recoveryShown)+'</code><div class="online-auth-actions"><button class="btn" data-on="recovery-copy">Copy code</button><button class="btn ghost" data-on="recovery-done">I saved it</button></div></div>';
 if(authMode==='signup')return '<div class="online-auth"><div class="online-mark">＋</div><h3>Create DaniLabs account</h3><p>Your username and password let you play from another device. Use a long passphrase.</p><label>Username<input id="onAuthUser" maxlength="24" autocomplete="username" placeholder="4–24 letters, numbers, _"></label><label>Password<input id="onAuthPass" type="password" maxlength="128" autocomplete="new-password" placeholder="At least 15 characters"></label><button class="btn" data-on="signup-submit">Create account</button><div class="online-auth-links"><button data-on="auth-login">Already have an account? Sign in</button></div></div>';
 if(authMode==='recover')return '<div class="online-auth"><div class="online-mark">↺</div><h3>Recover account</h3><p>Use the recovery code you saved when the account was created.</p><label>Username<input id="onAuthUser" maxlength="24" autocomplete="username"></label><label>Recovery code<input id="onRecovery" maxlength="64" autocomplete="off"></label><label>New password<input id="onAuthPass" type="password" maxlength="128" autocomplete="new-password" placeholder="At least 15 characters"></label><button class="btn" data-on="recover-submit">Reset password</button><div class="online-auth-links"><button data-on="auth-login">Back to sign in</button></div></div>';
 return '<div class="online-auth"><div class="online-mark">◎</div><h3>Play from any device</h3><p>Sign in with your DaniLabs username and password.</p><label>Username<input id="onAuthUser" maxlength="24" autocomplete="username"></label><label>Password<input id="onAuthPass" type="password" maxlength="128" autocomplete="current-password"></label><button class="btn" data-on="signin-submit">Sign in</button><div class="online-auth-links"><button data-on="auth-signup">Create account</button><button data-on="auth-recover">Forgot password?</button></div></div>'
}
function roomHTML(){
 if(serviceError)return '<div class="online-auth"><div class="online-mark">!</div><h3>Online service unavailable</h3><p>'+esc(serviceError)+'</p><button class="btn" data-on="retry">Retry connection</button></div>';
 if(recoveryShown)return authHTML();
 if(!signed())return authHTML();
 if(room){const turnSecs=Math.round((room.state?.meta?.turnMs||45000)/1000),graceSecs=Math.round((room.state?.meta?.reconnectGraceMs||60000)/1000);const me=members.find(m=>m.user_id===uid()),host=room.host_id===uid(),playing=room.status==='playing',finished=room.status==='finished',ready=!!(me&&me.ready);return '<div class="online-room"><div class="online-room-head"><div><small>ROOM CODE</small><b>'+esc(room.code)+'</b></div><div><span class="online-status '+esc(room.status)+'">'+esc(room.status)+'</span><small class="connection-state">'+esc(connectionState)+'</small></div></div><div class="online-members">'+members.map(m=>{const connected=Date.now()-Date.parse(m.last_seen_at||0)<graceSecs*1000;return '<div class="online-member" style="--c:'+HEX[m.color]+'"><i class="ludo-icon icon-'+esc(m.avatar||'avatar-1')+'"></i><span><b>'+esc(m.display_name||m.username||'Player')+'</b><small>@'+esc(m.username||'player')+' · '+NAMES[m.color]+' · '+(connected?'CONNECTED':'RECONNECTING')+'</small></span><em>'+(m.user_id===room.host_id?'HOST':m.ready?'READY':'WAIT')+'</em></div>'}).join('')+'</div>'+(!playing&&!finished&&host?'<div class="online-host-config"><label>Game<select id="roomVariant"><option value="classic" '+(room.variant==='classic'?'selected':'')+'>Classic Ludo</option><option value="color-cards" '+(room.variant==='color-cards'?'selected':'')+'>Color Cards</option></select></label><label>Color Cards match<select id="roomMode"><option value="round" '+(room.options?.mode!=='500'?'selected':'')+'>Single round</option><option value="500" '+(room.options?.mode==='500'?'selected':'')+'>Points to 500</option></select></label><button class="btn ghost" data-on="configure">Lock selection for start</button></div>':'')+(playing?'<p class="online-tip">Match is live. Turns have a '+turnSecs+'-second server timer. Reconnect grace is '+graceSecs+' seconds using the same account; the match never silently becomes offline. Color Cards timeout: draw one and end safely. Ludo timeout: the server rolls and, when required, makes the first legal move.</p>':finished?'<p class="online-tip">Match complete. You can close this finished room.</p>':'<div class="online-room-actions"><button class="btn '+(ready?'ghost':'')+'" data-on="ready">'+(ready?'Not ready':'Ready')+'</button>'+(host?'<button class="btn" data-on="start" '+(members.length!==room.max_players||members.some(m=>!m.ready)?'disabled':'')+'>Start match</button>':'')+'<button class="btn ghost" data-on="copy">Copy code</button></div>')+(playing?'<button class="btn" data-on="reconnect">Reconnect to game</button>':'')+'<button class="btn ghost online-leave" data-on="leave">'+(playing?'Exit view':finished?'Close finished room':'Leave room')+'</button></div>'}
 return '<div class="online-account"><div class="online-user"><span>●</span><div><b>@'+esc(username())+'</b><small>Signed in · works across devices</small></div><button class="btn ghost sm" data-on="signout">Sign out</button></div><div class="online-play-grid"><section><h3>Create private room</h3><p>Invite friends with a 6-character room code.</p><label>Players<select id="onPlayers"><option value="2">2 players</option><option value="3">3 players</option><option value="4">4 players</option></select></label><label>Game<select id="onVariant"><option value="classic">Classic Ludo</option><option value="color-cards">Color Cards</option></select></label><label>Color Cards format<select id="onMode"><option value="round">Single round</option><option value="500">Points to 500</option></select></label><label>Visibility<select id="onVisibility"><option value="private">Private · room code</option><option value="public" disabled>Public · not implemented yet</option></select></label><button class="btn" data-on="create">Create room</button></section><section><h3>Join room</h3><p>Enter the code shared by the host.</p><input id="onCode" maxlength="6" autocomplete="off" autocapitalize="characters" placeholder="ABC123"><button class="btn" data-on="join">Join room</button></section></div><details class="online-friends"><summary>Friends</summary><div class="online-friend-tools"><input id="onFriend" maxlength="24" autocomplete="off" placeholder="Username"><button class="btn ghost" data-on="friend-add">Add friend</button></div><div id="onFriendList"><p class="hint">Loading friends…</p></div></details><details class="online-friends"><summary>Account security</summary><div class="online-security"><label>Current password<input id="onCurrentPass" type="password" maxlength="128" autocomplete="current-password"></label><label>New password<input id="onNewPass" type="password" maxlength="128" autocomplete="new-password" placeholder="At least 15 characters"></label><button class="btn ghost" data-on="change-password">Change password</button><p class="hint">Changing your password signs out other devices.</p></div></details></div>'
}
function renderOnline(){const b=q('#onlineBody');if(!b)return;b.innerHTML=roomHTML();profileState();if(signed()&&!room&&!recoveryShown)loadFriends().catch(()=>{})}
async function bootAuth(){try{const d=await call('/auth?health=1');serviceError='';user=d.user||null;if(user)await resumeRoom();else{room=null;members=[];stopPoll();window.OnlineCards&&OnlineCards.clear()}}catch(e){serviceError=e.message||'Please try again later.';user=null;room=null;members=[];stopPoll();restoreNames();notice(serviceError,true)}profileState();renderOnline();checkInvites()}
async function openOnline(){modal('#mOnline');notice('');await bootAuth()}
async function authSubmit(action){if(busyNet)return;const u=(q('#onAuthUser')?.value||'').trim().toLowerCase(),p=q('#onAuthPass')?.value||'';busyNet=true;notice(action==='register'?'Creating account…':'Signing in…');try{const d=await call('/auth',{method:'POST',body:JSON.stringify({action,username:u,password:p})});user=d.user||null;recoveryShown=d.recoveryCode||'';authMode='login';notice(user?'Signed in':'');renderOnline();if(user&&!recoveryShown)await resumeRoom()}catch(e){notice(e.message,true)}finally{busyNet=false}}
async function recover(){if(busyNet)return;const username=(q('#onAuthUser')?.value||'').trim().toLowerCase(),recoveryCode=(q('#onRecovery')?.value||'').trim(),newPassword=q('#onAuthPass')?.value||'';busyNet=true;notice('Resetting password…');try{const d=await call('/auth',{method:'POST',body:JSON.stringify({action:'recover',username,recoveryCode,newPassword})});user=null;recoveryShown=d.recoveryCode||'';authMode='login';notice('Password reset. Save the new recovery code, then sign in.');renderOnline()}catch(e){notice(e.message,true)}finally{busyNet=false}}
async function changePassword(){const currentPassword=q('#onCurrentPass')?.value||'',newPassword=q('#onNewPass')?.value||'';if(busyNet)return;busyNet=true;try{const d=await call('/auth',{method:'POST',body:JSON.stringify({action:'change-password',currentPassword,newPassword})});user=d.user;notice('Password changed. Other devices were signed out.');renderOnline()}catch(e){notice(e.message,true)}finally{busyNet=false}}
async function signOut(){try{await call('/auth',{method:'POST',body:JSON.stringify({action:'logout'})})}catch(e){}user=null;room=null;members=[];recoveryShown='';stopPoll();restoreNames();window.OnlineCards&&OnlineCards.clear();renderOnline();profileState()}
async function createRoom(){if(busyNet)return;busyNet=true;notice('Creating room…');try{const players=+(q('#onPlayers')?.value||2),variant=q('#onVariant')?.value||'classic',mode=q('#onMode')?.value||'round';const d=await call('/room',{method:'POST',body:JSON.stringify({action:'create',players,variant,mode})});await setRoom(d.room)}catch(e){notice(e.message,true)}finally{busyNet=false}}
async function joinRoom(){if(busyNet)return;const code=(q('#onCode')?.value||'').trim().toUpperCase();if(!/^[A-Z0-9]{6}$/.test(code)){notice('Enter a 6-character room code.',true);return}busyNet=true;notice('Joining…');try{const d=await call('/room',{method:'POST',body:JSON.stringify({action:'join',code})});await setRoom(d.room)}catch(e){notice(e.message,true)}finally{busyNet=false}}
async function setRoom(r){room=r;lastVersion=-1;await refreshRoom();startPoll();renderOnline()}
async function resumeRoom(){if(!signed())return;try{const d=await call('/room?mine=1');if(d&&d.room){room=d.room;members=d.members||[];lastVersion=room.version??-1;startPoll();if((room.status==='playing'||room.status==='finished')&&room.state)applyState(room)}else{room=null;members=[];stopPoll()}renderOnline()}catch(e){if(/sign in/i.test(e.message)){user=null;room=null;members=[];stopPoll();renderOnline()}}}
async function refreshRoom(){if(!room||!signed())return;try{const d=await call('/room?code='+encodeURIComponent(room.code));room=d.room;members=d.members||[];if((room.status==='playing'||room.status==='finished')&&room.state&&(room.version!==lastVersion||lastRoomStatus!==room.status))applyState(room);lastVersion=room.version??lastVersion;lastRoomStatus=room.status;scheduleDeadline();renderOnline()}catch(e){notice('Reconnecting…');if(/not found|not in|sign in/i.test(e.message)){room=null;members=[];stopPoll();renderOnline()}}}
function paintMatchStatus(){let e=q('#onlineMatchStatus');if(!room||room.status!=='playing'){e?.remove();return}if(!e){e=document.createElement('div');e.id='onlineMatchStatus';e.className='online-match-status';document.body.appendChild(e)}const due=Date.parse(room.state?.meta?.deadlineAt||0),sec=Number.isFinite(due)?Math.max(0,Math.ceil((due-Date.now())/1000)):0;e.textContent=connectionState+' · '+sec+'s'}
function scheduleDeadline(){clearTimeout(deadlineTimer);const due=Date.parse(room?.state?.meta?.deadlineAt||0);if(room?.status==='playing'&&Number.isFinite(due))deadlineTimer=setTimeout(()=>sendAction('timeout'),Math.max(50,due-Date.now()+50))}
function startPoll(){clearTimeout(deadlineTimer);clearInterval(presenceTimer);if(!room?.id)return;window.DaniRealtime?.connect(room.id,()=>refreshRoom(),s=>{connectionState=s;renderOnline();if(s==='Connected')refreshRoom()});presenceTimer=setInterval(()=>{if(room&&signed())call('/room',{method:'POST',body:JSON.stringify({action:'presence',code:room.code})}).catch(()=>{})},15000);scheduleDeadline();clearInterval(statusTimer);statusTimer=setInterval(paintMatchStatus,500);paintMatchStatus()}
function stopPoll(){clearTimeout(deadlineTimer);clearInterval(presenceTimer);clearInterval(statusTimer);deadlineTimer=null;presenceTimer=null;statusTimer=null;q('#onlineMatchStatus')?.remove();window.DaniRealtime?.disconnect();connectionState='Disconnected'}
async function toggleReady(){const me=members.find(m=>m.user_id===uid());if(!me)return;try{await call('/room',{method:'POST',body:JSON.stringify({action:'ready',code:room.code,ready:!me.ready})});await refreshRoom()}catch(e){notice(e.message,true)}}
async function startMatch(){try{notice('Starting match…');const d=await call('/room',{method:'POST',body:JSON.stringify({action:'start',code:room.code})});room=d.room;await refreshRoom();modal('#mOnline',false)}catch(e){notice(e.message,true)}}
async function leaveRoom(){if(room&&room.status==='playing'){stopPoll();restoreNames();window.OnlineCards&&OnlineCards.clear();modal('#mOnline',false);show('home');notice('Reopen Online to return to the live match.');return}try{await call('/room',{method:'POST',body:JSON.stringify({action:'leave',code:room.code})})}catch(e){notice(e.message,true);return}room=null;members=[];stopPoll();restoreNames();renderOnline();show('home')}
function myColor(){const m=members.find(x=>x.user_id===uid());return m&&m.color||null}
function activeGame(){if(!room||room.status!=='playing'||!room.state||!room.state.game)return false;return room.state.game.kind==='color-cards'?!!(window.OnlineCards&&OnlineCards.isActive()):!!(G&&G.online&&G.onlineRoom===room.id)}
function applyNames(){if(!savedNames)savedNames=Object.fromEntries(COLORS.map(c=>[c,NAMES[c]]));members.forEach(m=>{if(m.color&&NAMES[m.color]!==undefined)NAMES[m.color]=(m.display_name||m.username||NAMES[m.color]).slice(0,12)})}
function restoreNames(){if(!savedNames)return;COLORS.forEach(c=>NAMES[c]=savedNames[c]);savedNames=null}
function friendlyMessage(m){let x=String(m||'');COLORS.forEach(c=>{x=x.replace(new RegExp('\\b'+c+'\\b','gi'),NAMES[c])});return x}
function applyState(r){
 if(!r||!r.state||!r.state.game)return;const st=r.state;room=r;applyNames();
 if(st.game.kind==='color-cards'){
  G=null;Snd.ac();Snd.music(1);st.message=friendlyMessage(st.message);
  if(window.OnlineCards)OnlineCards.applyState(st,r,members,myColor(),sendAction);
  if(st.game.winner)stopPoll();
  return
 }
 window.OnlineCards&&OnlineCards.clear();G=st.game;G.online=1;G.onlineRoom=r.id;G.bots=[];phase=st.phase||'roll';busy=false;
 const entering=startedRoom!==r.id||!q('#game').classList.contains('on');if(entering){startedRoom=r.id;buildBoard();show('game');Snd.ac();Snd.music(1)}
 say(friendlyMessage(st.message)||NAMES[cur()]+' to play');render();if(G.over)showOnlineOver()
}
function showOnlineOver(){if(!G||!G.over)return;stopPoll();Snd.music(0);q('#ranks').innerHTML=G.ranks.map((c,i)=>'<li style="--c:'+HEX[c]+'"><span>'+(['🥇','🥈','🥉','4️⃣'][i]||'')+'</span><b>'+esc(NAMES[c])+'</b></li>').join('');if(q('#victoryTitle'))q('#victoryTitle').textContent=NAMES[G.ranks[0]]+' wins!';if(q('#victorySub'))q('#victorySub').textContent='Online match complete';if(q('#bRematch'))q('#bRematch').hidden=true;modal('#mOver')}
function onlineTurnColor(){const g=room&&room.state&&room.state.game;if(!g)return null;return g.kind==='color-cards'?(g.players[g.turn]&&g.players[g.turn].id):(G?cur():null)}
async function sendAction(kind,payload={}){if(!activeGame()){toast('Online match is not ready');return false}if(!['catch','timeout'].includes(kind)&&myColor()!==onlineTurnColor()){toast('Wait for your turn');return false}if(busyNet){toast('Previous action is still pending');return false}busyNet=true;document.documentElement.classList.add('online-action-pending');try{const d=await call('/action',{method:'POST',body:JSON.stringify({code:room.code,kind,payload,version:room.version,actionId:(crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+'_'+Math.random().toString(36).slice(2))})});if(d.room){room=d.room;members=d.members||members;applyState(room);lastVersion=room.version}return true}catch(e){toast(e.message||'Online action failed');await refreshRoom();return false}finally{busyNet=false;document.documentElement.classList.remove('online-action-pending')}}
async function inviteFriend(playerId){if(!room||room.status!=='waiting')throw Error('Create a waiting room first');return call('/invitations',{method:'POST',body:JSON.stringify({action:'send',playerId,code:room.code})})}
async function loadFriends(){const box=q('#onFriendList');if(!box)return;try{const d=await call('/friends');const a=d.friends||[];box.innerHTML=a.length?a.map(f=>'<div class="online-friend"><span><b>@'+esc(f.username)+'</b><small>'+esc(f.status)+'</small></span>'+(f.direction==='received'&&f.status==='pending'?'<button class="btn ghost sm" data-on="friend-accept" data-user="'+esc(f.user_id)+'">Accept</button>':'')+'</div>').join(''):'<p class="hint">No friends yet. Add someone by username.</p>'}catch(e){box.innerHTML='<p class="hint">Friends unavailable.</p>'}}
async function addFriend(){const name=(q('#onFriend')?.value||'').trim();if(!name)return;try{await call('/friends',{method:'POST',body:JSON.stringify({username:name})});q('#onFriend').value='';notice('Friend request updated');await loadFriends()}catch(e){notice(e.message,true)}}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-on]');if(!b)return;const a=b.dataset.on;
 if(a==='retry'){serviceError='';notice('Checking online service…');await bootAuth()}else if(a==='auth-login'){authMode='login';notice('');renderOnline()}else if(a==='auth-signup'){authMode='signup';notice('');renderOnline()}else if(a==='auth-recover'){authMode='recover';notice('');renderOnline()}
 else if(a==='signin-submit')authSubmit('login');else if(a==='signup-submit')authSubmit('register');else if(a==='recover-submit')recover();else if(a==='change-password')changePassword();else if(a==='signout')signOut();
 else if(a==='recovery-copy'){try{await navigator.clipboard.writeText(recoveryShown);notice('Recovery code copied')}catch(x){notice('Copy the recovery code manually.')}}else if(a==='recovery-done'){recoveryShown='';notice('');renderOnline();if(signed())await resumeRoom()}
 else if(a==='reconnect'){connectionState='Connecting';startPoll();await refreshRoom();if(room?.state)applyState(room);modal('#mOnline',false)}else if(a==='configure'){try{const d=await call('/room',{method:'POST',body:JSON.stringify({action:'configure',code:room.code,variant:q('#roomVariant')?.value,mode:q('#roomMode')?.value})});room=d.room;members=d.members||members;renderOnline()}catch(x){notice(x.message,true)}}else if(a==='create')createRoom();else if(a==='join')joinRoom();else if(a==='ready')toggleReady();else if(a==='start')startMatch();else if(a==='leave')leaveRoom();else if(a==='copy'){try{await navigator.clipboard.writeText(room.code);notice('Room code copied')}catch(x){notice('Room code: '+room.code)}}else if(a==='friend-add')addFriend();else if(a==='friend-accept'){try{await call('/friends',{method:'POST',body:JSON.stringify({acceptUserId:b.dataset.user})});notice('Friend added');await loadFriends()}catch(x){notice(x.message,true)}}});
q('#bOnline')&&(q('#bOnline').onclick=()=>{Snd.play('tap');openOnline()});q('#nOnline')&&(q('#nOnline').onclick=()=>{Snd.play('tap');openOnline()});q('#bFriends')&&(q('#bFriends').onclick=()=>{Snd.play('tap');openOnline()});q('#nFriends')&&(q('#nFriends').onclick=()=>{Snd.play('tap');openOnline()});
window.OnlinePlay={invite:inviteFriend,configured:()=>!serviceError,signed,activeGame,myColor,open:openOnline,joinCode:async code=>{await openOnline();const el=q('#onCode');if(el)el.value=code;return joinRoom()},requestRoll:()=>sendAction('roll'),requestMove:(c,i)=>c===myColor()?sendAction('move',{token:i}):Promise.resolve(false),leave:leaveRoom,refresh:refreshRoom,prepareLocal:()=>{stopPoll();restoreNames();window.OnlineCards&&OnlineCards.clear()}};
bootAuth();
})();
