'use strict';
/* DaniLabs online client. Server-authoritative match actions; no private power logic is used online. */
(function(){
const cfg=window.DaniOnlineConfig||{},API='/api/online';
let clerk=null,room=null,members=[],pollTimer=null,busyNet=false,lastVersion=-1,lastRoomStatus='',startedRoom='';
const q=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const configured=()=>!!cfg.clerkPublishableKey;
const signed=()=>!!(clerk&&clerk.user&&clerk.session);
const uid=()=>signed()?clerk.user.id:null;
const username=()=>signed()?(clerk.user.username||clerk.user.firstName||'Player'):'Player';
const token=async()=>signed()?clerk.session.getToken():null;
const notice=(m,bad=false)=>{const e=q('#onlineMsg');if(!e)return;e.textContent=m||'';e.classList.toggle('err',!!bad)};
async function call(path,opts={}){const t=await token(),headers=Object.assign({'Content-Type':'application/json'},opts.headers||{});if(t)headers.Authorization='Bearer '+t;const r=await fetch(API+path,Object.assign({},opts,{headers}));let data=null;try{data=await r.json()}catch(e){}if(!r.ok)throw new Error((data&&data.error)||('Request failed '+r.status));return data}
function profileState(){const el=q('#pName')&&q('#pName').nextElementSibling;if(!el)return;if(signed()){el.innerHTML='<i></i> ONLINE · @'+esc(username())}else el.innerHTML='<i></i> OFFLINE'}
function authHTML(){if(!configured())return '<div class="online-empty"><b>Online service setup needed</b><p>The game code is ready, but the production authentication/database connection has not been attached yet.</p></div>';
 if(!signed())return '<div class="online-auth"><div class="online-mark">◎</div><h3>Play from any device</h3><p>Sign in or create an account. Accounts use Username + Password.</p><div class="online-auth-actions"><button class="btn" data-on="signin">Sign in</button><button class="btn ghost" data-on="signup">Create account</button></div></div>';
 return ''}
function roomHTML(){if(!signed())return authHTML();if(room){const me=members.find(m=>m.user_id===uid()),host=room.host_id===uid(),playing=room.status==='playing',ready=!!(me&&me.ready);return '<div class="online-room"><div class="online-room-head"><div><small>ROOM CODE</small><b>'+esc(room.code)+'</b></div><span class="online-status '+esc(room.status)+'">'+esc(room.status)+'</span></div><div class="online-members">'+members.map(m=>'<div class="online-member" style="--c:'+HEX[m.color]+'"><i></i><span><b>'+esc(m.display_name||m.username||'Player')+'</b><small>@'+esc(m.username||'player')+' · '+NAMES[m.color]+'</small></span><em>'+(m.user_id===room.host_id?'HOST':m.ready?'READY':'WAIT')+'</em></div>').join('')+'</div>'+(playing?'<p class="online-tip">Match is live. Open the board and play only when it is your color\'s turn.</p>':'<div class="online-room-actions"><button class="btn '+(ready?'ghost':'')+'" data-on="ready">'+(ready?'Not ready':'Ready')+'</button>'+(host?'<button class="btn" data-on="start" '+(members.length<2||members.some(m=>!m.ready)?'disabled':'')+'>Start match</button>':'')+'<button class="btn ghost" data-on="copy">Copy code</button></div>')+'<button class="btn ghost online-leave" data-on="leave">'+(playing?'Exit view':'Leave room')+'</button></div>'}
 return '<div class="online-account"><div class="online-user"><span>●</span><div><b>@'+esc(username())+'</b><small>Signed in · account works across devices</small></div><button class="btn ghost sm" data-on="signout">Sign out</button></div><div class="online-play-grid"><section><h3>Create private room</h3><p>Invite friends with a 6-character room code.</p><label>Players<select id="onPlayers"><option value="2">2 players</option><option value="3">3 players</option><option value="4">4 players</option></select></label><label>Mode<select id="onVariant"><option value="classic">Classic</option><option value="quick">Quick</option><option value="rush">Rush</option></select></label><button class="btn" data-on="create">Create room</button></section><section><h3>Join room</h3><p>Enter the code shared by the host.</p><input id="onCode" maxlength="6" autocomplete="off" autocapitalize="characters" placeholder="ABC123"><button class="btn" data-on="join">Join room</button></section></div><details class="online-friends"><summary>Friends</summary><div class="online-friend-tools"><input id="onFriend" maxlength="32" autocomplete="off" placeholder="Username"><button class="btn ghost" data-on="friend-add">Add friend</button></div><div id="onFriendList"><p class="hint">Loading friends…</p></div></details></div>'}
function renderOnline(){const b=q('#onlineBody');if(!b)return;b.innerHTML=roomHTML();profileState();if(signed()&&!room)loadFriends().catch(()=>{})}
async function initClerk(){if(!configured()||!window.Clerk)return;try{clerk=new window.Clerk(cfg.clerkPublishableKey);await clerk.load();clerk.addListener(()=>{profileState();renderOnline();if(signed())resumeRoom().catch(()=>{});else stopPoll()});profileState();if(signed())await resumeRoom()}catch(e){notice('Online sign-in could not start.',true)}}
async function openOnline(){renderOnline();modal('#mOnline');if(configured()&&!clerk)await initClerk();renderOnline();if(signed())await resumeRoom()}
async function createRoom(){if(busyNet)return;busyNet=true;notice('Creating room…');try{const players=+(q('#onPlayers')?.value||2),variant=q('#onVariant')?.value||'classic';const d=await call('/room',{method:'POST',body:JSON.stringify({action:'create',players,variant})});await setRoom(d.room)}catch(e){notice(e.message,true)}finally{busyNet=false}}
async function joinRoom(){if(busyNet)return;const code=(q('#onCode')?.value||'').trim().toUpperCase();if(!/^[A-Z0-9]{6}$/.test(code)){notice('Enter a 6-character room code.',true);return}busyNet=true;notice('Joining…');try{const d=await call('/room',{method:'POST',body:JSON.stringify({action:'join',code})});await setRoom(d.room)}catch(e){notice(e.message,true)}finally{busyNet=false}}
async function setRoom(r){room=r;lastVersion=-1;await refreshRoom();startPoll();renderOnline()}
async function resumeRoom(){try{const d=await call('/room?mine=1');if(d&&d.room){room=d.room;members=d.members||[];lastVersion=room.version??-1;startPoll();if(room.status==='playing'&&room.state)applyState(room)}else{room=null;members=[];stopPoll()}renderOnline()}catch(e){}}
async function refreshRoom(){if(!room)return;try{const d=await call('/room?code='+encodeURIComponent(room.code));room=d.room;members=d.members||[];if(room.status==='playing'&&room.state&&(room.version!==lastVersion||lastRoomStatus!==room.status))applyState(room);lastVersion=room.version??lastVersion;lastRoomStatus=room.status;renderOnline()}catch(e){if(/not found|not in/i.test(e.message)){room=null;members=[];stopPoll();renderOnline()}}}
function startPoll(){stopPoll();pollTimer=setInterval(()=>{if(!document.hidden)refreshRoom()},850)}function stopPoll(){clearInterval(pollTimer);pollTimer=null}
async function toggleReady(){const me=members.find(m=>m.user_id===uid());if(!me)return;try{await call('/room',{method:'POST',body:JSON.stringify({action:'ready',code:room.code,ready:!me.ready})});await refreshRoom()}catch(e){notice(e.message,true)}}
async function startMatch(){try{notice('Starting match…');const d=await call('/room',{method:'POST',body:JSON.stringify({action:'start',code:room.code})});room=d.room;await refreshRoom();modal('#mOnline',false)}catch(e){notice(e.message,true)}}
async function leaveRoom(){if(room&&room.status==='playing'){stopPoll();modal('#mOnline',false);show('home');notice('You can reopen Online to return to the live match.');return}try{await call('/room',{method:'POST',body:JSON.stringify({action:'leave',code:room.code})})}catch(e){notice(e.message,true);return}room=null;members=[];stopPoll();renderOnline();show('home')}
function myColor(){const m=members.find(x=>x.user_id===uid());return m&&m.color||null}
function activeGame(){return !!(room&&room.status==='playing'&&G&&G.online&&G.onlineRoom===room.id)}
function applyNames(){members.forEach(m=>{if(m.color&&NAMES[m.color]!==undefined)NAMES[m.color]=(m.display_name||m.username||NAMES[m.color]).slice(0,12)})}
function friendlyMessage(m){let x=String(m||'');COLORS.forEach(c=>{x=x.replace(new RegExp('\\b'+c+'\\b','gi'),NAMES[c])});return x}
function applyState(r){if(!r||!r.state||!r.state.game)return;const st=r.state;room=r;applyNames();G=st.game;G.online=1;G.onlineRoom=r.id;G.bots=[];G.matchPower={};G.secretPowers={};phase=st.phase||'roll';busy=false;const entering=startedRoom!==r.id||!q('#game').classList.contains('on');if(entering){startedRoom=r.id;buildBoard();show('game');Snd.ac();Snd.music(1)}say(friendlyMessage(st.message)||NAMES[cur()]+' to play');render();if(G.over)showOnlineOver()}
function showOnlineOver(){if(!G||!G.over)return;Snd.music(0);q('#ranks').innerHTML=G.ranks.map((c,i)=>'<li style="--c:'+HEX[c]+'"><span>'+(['🥇','🥈','🥉','4️⃣'][i]||'')+'</span><b>'+esc(NAMES[c])+'</b></li>').join('');if(q('#victoryTitle'))q('#victoryTitle').textContent=NAMES[G.ranks[0]]+' wins!';if(q('#victorySub'))q('#victorySub').textContent='Online match complete';if(q('#bRematch'))q('#bRematch').hidden=true;modal('#mOver')}
async function sendAction(kind,payload={}){if(!activeGame()){toast('Online match is not ready');return false}if(myColor()!==cur()){toast('Wait for your turn');return false}if(busyNet)return false;busyNet=true;try{const d=await call('/action',{method:'POST',body:JSON.stringify({code:room.code,kind,payload,version:room.version})});if(d.room){room=d.room;members=d.members||members;applyState(room);lastVersion=room.version}return true}catch(e){toast(e.message||'Online action failed');await refreshRoom();return false}finally{busyNet=false}}
async function loadFriends(){const box=q('#onFriendList');if(!box)return;try{const d=await call('/friends');const a=d.friends||[];box.innerHTML=a.length?a.map(f=>'<div class="online-friend"><span><b>@'+esc(f.username)+'</b><small>'+esc(f.status)+'</small></span>'+(f.direction==='received'&&f.status==='pending'?'<button class="btn ghost sm" data-on="friend-accept" data-user="'+esc(f.user_id)+'">Accept</button>':'')+'</div>').join(''):'<p class="hint">No friends yet. Add someone by username.</p>'}catch(e){box.innerHTML='<p class="hint">Friends unavailable.</p>'}}
async function addFriend(){const name=(q('#onFriend')?.value||'').trim();if(!name)return;try{await call('/friends',{method:'POST',body:JSON.stringify({username:name})});q('#onFriend').value='';notice('Friend request updated');await loadFriends()}catch(e){notice(e.message,true)}}
async function signOut(){if(!clerk)return;await clerk.signOut();room=null;members=[];stopPoll();renderOnline()}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-on]');if(!b)return;const a=b.dataset.on;if(a==='signin'){if(clerk)clerk.openSignIn()}else if(a==='signup'){if(clerk)clerk.openSignUp()}else if(a==='signout')signOut();else if(a==='create')createRoom();else if(a==='join')joinRoom();else if(a==='ready')toggleReady();else if(a==='start')startMatch();else if(a==='leave')leaveRoom();else if(a==='copy'){try{await navigator.clipboard.writeText(room.code);notice('Room code copied')}catch(x){notice('Room code: '+room.code)}}else if(a==='friend-add')addFriend();else if(a==='friend-accept'){try{await call('/friends',{method:'POST',body:JSON.stringify({acceptUserId:b.dataset.user})});notice('Friend added');await loadFriends()}catch(x){notice(x.message,true)}}});
q('#bOnline')&&(q('#bOnline').onclick=()=>{Snd.play('tap');openOnline()});q('#bFriends')&&(q('#bFriends').onclick=()=>{Snd.play('tap');openOnline()});q('#nFriends')&&(q('#nFriends').onclick=()=>{Snd.play('tap');openOnline()});
window.OnlinePlay={configured,signed,activeGame,myColor,open:openOnline,requestRoll:()=>sendAction('roll'),requestMove:(c,i)=>c===myColor()?sendAction('move',{token:i}):Promise.resolve(false),leave:leaveRoom,refresh:refreshRoom};
initClerk();
})();
