'use strict';
window.DaniRewards=(()=>{
 const q=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch])),localKey='ldb_cosmetics';
 async function api(path,opts={}){const r=await fetch('/api/online'+path,{credentials:'same-origin',...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}
 function apply(load){if(!load)return;localStorage.setItem(localKey,JSON.stringify(load));const e=document.documentElement;e.dataset.avatarTheme=load.avatar||'avatar-1';e.dataset.boardTheme=load.board||'board-royal';e.dataset.pawnTheme=load.pawn||'pawn-classic';e.dataset.cardBack=load.card_back||'cards-royal';e.dataset.profileFrame=load.frame||'frame-none'}
 function cached(){try{apply(JSON.parse(localStorage.getItem(localKey)||'null'))}catch(e){}}
 function wallet(n){const b=q('#coinBalance');if(b)b.textContent=String(n??0)}
 async function open(tab='daily'){modal('#mRewards');await refresh(tab)}
 async function refresh(tab='daily'){const box=q('#rewardsBody');if(!box)return;box.innerHTML='<p class="hint">Loading verified rewards…</p>';if(!navigator.onLine){cached();box.innerHTML='<p class="hint">Rewards require a connection and signed-in account. Cached equipped cosmetics can still display offline; offline play never changes online ownership or coin balance.</p>';return}try{const d=await api('/rewards');wallet(d.balance);apply(d.loadout);const daily=d.daily.days.map(x=>'<div class="reward-day '+x.state+'"><b>Day '+x.day+'</b><span>🪙 '+x.coins+'</span><small>'+x.state+'</small></div>').join(''),missions=d.missions.map(m=>'<div class="reward-line"><span><b>'+esc(m.label)+'</b><small>'+Math.min(m.progress,m.target)+' / '+m.target+' · 🪙 '+m.coins+'</small></span>'+(m.complete&&!m.claimed?'<button class="btn sm" data-reward="mission" data-key="'+m.key+'">Claim</button>':'<em>'+(m.claimed?'Claimed':'In progress')+'</em>')+'</div>').join(''),shop=d.shop.map(x=>'<div class="shop-item"><div class="cosmetic-preview '+esc(x.type)+'" data-item="'+esc(x.id)+'"></div><span><b>'+esc(x.name)+'</b><small>'+esc(x.type.replace('_',' '))+' · 🪙 '+x.price+'</small></span>'+(x.owned?'<button class="btn ghost sm" data-reward="equip" data-item="'+x.id+'">Equip</button>':'<button class="btn sm" data-reward="buy" data-item="'+x.id+'">Unlock</button>')+'</div>').join('');
 box.innerHTML='<div class="reward-tabs"><button data-reward="tab" data-tab="daily">Daily</button><button data-reward="tab" data-tab="missions">Missions</button><button data-reward="tab" data-tab="shop">Cosmetics</button><button data-reward="tab" data-tab="leaders">Leaderboards</button></div><p class="hint">Earned coins have no cash value. Daily reset: 00:00 UTC. Missing a day resets the calendar to Day 1; after Day 7 it cycles to Day 1.</p><section data-pane="daily" '+(tab!=='daily'?'hidden':'')+'><div class="daily-grid">'+daily+'</div>'+(d.daily.claimable?'<button class="btn" data-reward="daily">Claim today</button>':'<p class="hint">Today’s reward is claimed.</p>')+'</section><section data-pane="missions" '+(tab!=='missions'?'hidden':'')+'>'+missions+'<p class="hint">Only verified completed online matches count. Offline, abandoned and forfeited matches do not.</p></section><section data-pane="shop" '+(tab!=='shop'?'hidden':'')+'>'+shop+'<p class="hint">Cosmetics affect appearance only and provide no gameplay advantage.</p></section><section data-pane="leaders" '+(tab!=='leaders'?'hidden':'')+'><div class="row"><button class="btn ghost sm" data-reward="leader" data-game="classic">Ludo</button><button class="btn ghost sm" data-reward="leader" data-game="color-cards">Color Cards</button></div><div id="leaderBody"><p class="hint">Choose a leaderboard.</p></div></section>';
 }catch(e){box.innerHTML='<p class="err">'+esc(e.message)+'</p>'}}
 async function act(a,b){if(a==='tab')return refresh(b.dataset.tab);if(a==='daily')await api('/rewards',{method:'POST',body:JSON.stringify({action:'claim-daily'})});else if(a==='mission')await api('/rewards',{method:'POST',body:JSON.stringify({action:'claim-mission',missionKey:b.dataset.key})});else if(a==='buy'){if(!confirm('Unlock this cosmetic using earned coins?'))return;await api('/rewards',{method:'POST',body:JSON.stringify({action:'buy',itemId:b.dataset.item})})}else if(a==='equip')await api('/rewards',{method:'POST',body:JSON.stringify({action:'equip',itemId:b.dataset.item})});else if(a==='leader'){const d=await api('/leaderboard?game='+encodeURIComponent(b.dataset.game)),box=q('#leaderBody');box.innerHTML=d.entries.length?'<p class="hint">'+esc(d.eligibility)+' · Ranked by '+esc(d.ranking)+'.</p>'+d.entries.map(x=>'<div class="reward-line"><b>#'+x.rank+' '+esc(x.displayName)+'</b><span>'+x.wins+' wins · '+x.games+' games · '+x.winRate+'%</span></div>').join(''):'<p class="hint">No eligible verified matches yet.</p>';return}await refresh(a==='mission'?'missions':a==='buy'||a==='equip'?'shop':'daily')}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-reward]');if(b)act(b.dataset.reward,b).catch(x=>toast(x.message))});cached();return{open,refresh};
})();