import {requireUser,requireSameOrigin} from '../_auth.js';import {db,enc} from '../_db.js';import {pairKey,validPlayerId,canSocial} from '../_social-policy.js';
const send=(r,s,d)=>r.status(s).json(d);
async function blocks(id){return await db('online_blocks?or=(blocker_id.eq.'+enc(id)+',blocked_id.eq.'+enc(id)+')&select=blocker_id,blocked_id')||[]}
async function findPlayer(id){const a=await db('online_profiles?player_id=eq.'+enc(String(id).toUpperCase())+'&select=user_id,player_id,display_name,avatar&limit=1');return a?.[0]}
export default async function handler(req,res){try{const u=await requireUser(req),bs=await blocks(u.id);if(req.method==='GET'){const rel=await db('online_friends?or=(requester_id.eq.'+enc(u.id)+',addressee_id.eq.'+enc(u.id)+')&select=*&order=created_at.desc')||[],ids=[...new Set(rel.flatMap(x=>[x.requester_id,x.addressee_id]).filter(x=>x!==u.id))],ps=ids.length?await db('online_profiles?user_id=in.('+ids.map(enc).join(',')+')&select=user_id,player_id,display_name,avatar,last_seen'):[],map=Object.fromEntries((ps||[]).map(p=>[p.user_id,p]));return send(res,200,{friends:rel.map(x=>{const oid=x.requester_id===u.id?x.addressee_id:x.requester_id,p=map[oid]||{};return{user_id:oid,player_id:p.player_id,display_name:p.display_name||'Player',avatar:p.avatar||'avatar-1',status:x.status,direction:x.requester_id===u.id?'sent':'received'}}),blocked:bs.filter(x=>x.blocker_id===u.id).map(x=>x.blocked_id)})}if(req.method!=='POST')return send(res,405,{error:'Method not allowed'});requireSameOrigin(req);const b=req.body||{},action=String(b.action||'send'),other=await findPlayer(b.playerId);if(!other||!validPlayerId(b.playerId))return send(res,404,{error:'Player ID not found'});if(other.user_id===u.id)return send(res,400,{error:'That is your account'});const key=pairKey(u.id,other.user_id),old=(await db('online_friends?pair_key=eq.'+enc(key)+'&select=*&limit=1'))?.[0];
 if(action==='block'){await db('online_blocks',{method:'POST',body:{blocker_id:u.id,blocked_id:other.user_id},prefer:'resolution=ignore-duplicates,return=minimal'});if(old)await db('online_friends?pair_key=eq.'+enc(key),{method:'DELETE'});return send(res,200,{ok:true})}
 if(action==='unblock'){await db('online_blocks?blocker_id=eq.'+enc(u.id)+'&blocked_id=eq.'+enc(other.user_id),{method:'DELETE'});return send(res,200,{ok:true})}
 if(!canSocial(u.id,other.user_id,bs))return send(res,403,{error:'Social actions are unavailable for this player'});
 if(action==='send'){if(old)return send(res,409,{error:'A friendship or request already exists'});await db('online_friends',{method:'POST',body:{pair_key:key,requester_id:u.id,addressee_id:other.user_id,status:'pending'}})}
 else if(action==='accept'){if(!old||old.addressee_id!==u.id||old.status!=='pending')return send(res,404,{error:'Friend request not found'});await db('online_friends?pair_key=eq.'+enc(key),{method:'PATCH',body:{status:'accepted'}})}
 else if(action==='decline'){if(!old||old.addressee_id!==u.id||old.status!=='pending')return send(res,404,{error:'Friend request not found'});await db('online_friends?pair_key=eq.'+enc(key),{method:'DELETE'})}
 else if(action==='cancel'){if(!old||old.requester_id!==u.id||old.status!=='pending')return send(res,404,{error:'Friend request not found'});await db('online_friends?pair_key=eq.'+enc(key),{method:'DELETE'})}
 else if(action==='remove'){if(!old||old.status!=='accepted')return send(res,404,{error:'Friendship not found'});await db('online_friends?pair_key=eq.'+enc(key),{method:'DELETE'})}
 else return send(res,400,{error:'Unknown friend action'});return send(res,200,{ok:true})}catch(e){return send(res,e.status&&e.status<600?e.status:500,{error:e.message||'Friends error'})}}
