import {requireUser,requireSameOrigin} from '../_auth.js';import {db,enc} from '../_db.js';import {validPlayerId,canSocial} from '../_social-policy.js';import {broadcastRoom} from '../_realtime.js';
const send=(r,s,d)=>r.status(s).json(d);
export default async function handler(req,res){try{const u=await requireUser(req);if(req.method==='GET'){const rows=await db('online_invites?recipient_id=eq.'+enc(u.id)+'&status=eq.pending&expires_at=gt.'+enc(new Date().toISOString())+'&select=*&order=created_at.desc')||[];const ids=[...new Set(rows.map(x=>x.sender_id))],ps=ids.length?await db('online_profiles?user_id=in.('+ids.map(enc).join(',')+')&select=user_id,player_id,display_name,avatar'):[],map=Object.fromEntries((ps||[]).map(p=>[p.user_id,p]));return send(res,200,{invitations:rows.map(x=>({...x,sender:map[x.sender_id]||null}))})}if(req.method!=='POST')return send(res,405,{error:'Method not allowed'});requireSameOrigin(req);const b=req.body||{},action=String(b.action||'send');
 if(action==='send'){const p=(await db('online_profiles?player_id=eq.'+enc(String(b.playerId||'').toUpperCase())+'&select=user_id,player_id,display_name&limit=1'))?.[0];if(!p||!validPlayerId(b.playerId))return send(res,404,{error:'Player ID not found'});const blocks=await db('online_blocks?or=(and(blocker_id.eq.'+enc(u.id)+',blocked_id.eq.'+enc(p.user_id)+'),and(blocker_id.eq.'+enc(p.user_id)+',blocked_id.eq.'+enc(u.id)+'))&select=blocker_id,blocked_id')||[];if(!canSocial(u.id,p.user_id,blocks))return send(res,403,{error:'Invitations are unavailable for this player'});const r=(await db('online_rooms?code=eq.'+enc(String(b.code||'').toUpperCase())+'&host_id=eq.'+enc(u.id)+'&status=eq.waiting&select=id,code,max_players&limit=1'))?.[0];if(!r)return send(res,404,{error:'Waiting room not found or you are not the host'});const ms=await db('online_members?room_id=eq.'+enc(r.id)+'&select=user_id')||[];if(ms.length>=r.max_players)return send(res,409,{error:'Room is full'});await db('online_invites',{method:'POST',body:{sender_id:u.id,recipient_id:p.user_id,room_id:r.id},prefer:'resolution=ignore-duplicates,return=minimal'});return send(res,200,{ok:true})}
 const row=(await db('online_invites?id=eq.'+enc(b.inviteId)+'&select=*&limit=1'))?.[0];if(!row)return send(res,404,{error:'Invitation not found'});
 if(action==='cancel'){if(row.sender_id!==u.id)return send(res,403,{error:'Only the sender can cancel'});await db('online_invites?id=eq.'+enc(row.id),{method:'PATCH',body:{status:'cancelled'}});return send(res,200,{ok:true})}
 if(row.recipient_id!==u.id)return send(res,403,{error:'This invitation is not yours'});if(row.status!=='pending'||Date.now()>Date.parse(row.expires_at)){if(row.status==='pending')await db('online_invites?id=eq.'+enc(row.id),{method:'PATCH',body:{status:'expired'}});return send(res,409,{error:'Invitation expired or is no longer available'})}
 if(action==='decline'){await db('online_invites?id=eq.'+enc(row.id),{method:'PATCH',body:{status:'declined'}});return send(res,200,{ok:true})}
 if(action==='accept'){const bs=await db('online_blocks?or=(and(blocker_id.eq.'+enc(u.id)+',blocked_id.eq.'+enc(row.sender_id)+'),and(blocker_id.eq.'+enc(row.sender_id)+',blocked_id.eq.'+enc(u.id)+'))&select=blocker_id,blocked_id')||[];if(!canSocial(u.id,row.sender_id,bs))return send(res,403,{error:'This invitation is blocked'});const r=(await db('online_rooms?id=eq.'+enc(row.room_id)+'&select=*&limit=1'))?.[0],ms=r?await db('online_members?room_id=eq.'+enc(r.id)+'&select=*&order=seat.asc'):[];if(!r||r.status!=='waiting'||ms.length>=r.max_players)return send(res,409,{error:'Room is no longer joinable'});const existing=ms.find(m=>m.user_id===u.id);if(!existing){const used=new Set(ms.map(m=>m.seat));let seat=0;while(used.has(seat)&&seat<4)seat++;const colors=['red',r.max_players===2?'yellow':'green','yellow','blue'],p=(await db('online_profiles?user_id=eq.'+enc(u.id)+'&select=display_name,avatar&limit=1'))?.[0]||{};await db('online_members',{method:'POST',body:{room_id:r.id,user_id:u.id,seat,color:colors[seat],ready:false,username:u.username,display_name:p.display_name||u.display_name||u.username,avatar:p.avatar||'avatar-1'}})}await db('online_invites?id=eq.'+enc(row.id),{method:'PATCH',body:{status:'accepted'}});await broadcastRoom(r.id,'room_changed',{reason:'invite-accepted'});return send(res,200,{ok:true,code:r.code})}
 return send(res,400,{error:'Unknown invitation action'})}catch(e){return send(res,e.status&&e.status<600?e.status:500,{error:e.message||'Invitation error'})}}
