import {requireUser,requireSameOrigin} from '../_auth.js';import {db,enc} from '../_db.js';import {RESET_TZ,DAILY_COINS,MISSIONS,COSMETICS,utcDay,periodKey,nextStreak} from '../_rewards-policy.js';
const send=(r,s,d)=>r.status(s).json(d);
async function wallet(id){const a=await db('reward_wallets?user_id=eq.'+enc(id)+'&select=balance&limit=1');return a?.[0]?.balance||0}
async function state(u){const now=new Date(),today=utcDay(now),claims=await db('daily_reward_claims?user_id=eq.'+enc(u.id)+'&select=reward_date,streak_day,coins,created_at&order=reward_date.desc&limit=7')||[],last=claims[0],next=nextStreak(last?.reward_date,last?.streak_day,now),keys=[periodKey('daily',now),periodKey('weekly',now)],prog=await db('mission_progress?user_id=eq.'+enc(u.id)+'&period_key=in.('+keys.map(enc).join(',')+')&select=mission_key,period_key,progress,claimed')||[],pm=Object.fromEntries(prog.map(x=>[x.mission_key+'|'+x.period_key,x])),owned=await db('cosmetic_inventory?user_id=eq.'+enc(u.id)+'&select=item_id')||[],load=(await db('cosmetic_loadouts?user_id=eq.'+enc(u.id)+'&select=*&limit=1'))?.[0]||{avatar:'avatar-1',frame:'frame-none',board:'board-royal',pawn:'pawn-classic',card_back:'cards-royal'};
 return{serverTime:now.toISOString(),resetTimezone:RESET_TZ,balance:await wallet(u.id),daily:{today,claimable:next!==null,nextDay:next||last?.streak_day||1,days:DAILY_COINS.map((coins,i)=>({day:i+1,coins,state:last?.reward_date===today&&last.streak_day===i+1?'claimed':next===i+1?'available':'upcoming'}))},missions:MISSIONS.map(m=>{const k=periodKey(m.period,now),x=pm[m.key+'|'+k]||{};return{...m,periodKey:k,progress:Number(x.progress||0),claimed:!!x.claimed,complete:Number(x.progress||0)>=m.target}}),shop:COSMETICS.map(x=>({...x,owned:owned.some(o=>o.item_id===x.id)})),loadout:load}}
export default async function handler(req,res){try{const u=await requireUser(req);if(req.method==='GET')return send(res,200,await state(u));if(req.method!=='POST')return send(res,405,{error:'Method not allowed'});requireSameOrigin(req);const b=req.body||{},action=String(b.action||'');
 if(action==='claim-daily'){const now=new Date(),today=utcDay(now),last=(await db('daily_reward_claims?user_id=eq.'+enc(u.id)+'&select=reward_date,streak_day&order=reward_date.desc&limit=1'))?.[0],day=nextStreak(last?.reward_date,last?.streak_day,now);if(day===null)return send(res,409,{error:'Today’s reward is already claimed'});await db('rpc/claim_daily_reward',{method:'POST',body:{p_user:u.id,p_day:today,p_streak:day,p_coins:DAILY_COINS[day-1]}});return send(res,200,await state(u))}
 if(action==='claim-mission'){const m=MISSIONS.find(x=>x.key===b.missionKey);if(!m)return send(res,404,{error:'Mission not found'});const pk=periodKey(m.period,new Date());await db('rpc/claim_mission_reward',{method:'POST',body:{p_user:u.id,p_mission:m.key,p_period:pk,p_target:m.target,p_coins:m.coins}});return send(res,200,await state(u))}
 if(action==='buy'){const item=COSMETICS.find(x=>x.id===b.itemId);if(!item)return send(res,404,{error:'Cosmetic not found'});await db('rpc/purchase_cosmetic',{method:'POST',body:{p_user:u.id,p_item:item.id,p_price:item.price}});return send(res,200,await state(u))}
 if(action==='equip'){const item=COSMETICS.find(x=>x.id===b.itemId);if(!item)return send(res,404,{error:'Cosmetic not found'});const owned=(await db('cosmetic_inventory?user_id=eq.'+enc(u.id)+'&item_id=eq.'+enc(item.id)+'&select=item_id&limit=1'))?.[0];if(!owned)return send(res,403,{error:'Unlock this cosmetic first'});const col=item.type==='card_back'?'card_back':item.type;await db('cosmetic_loadouts?on_conflict=user_id',{method:'POST',body:{user_id:u.id,[col]:item.id,updated_at:new Date().toISOString()},prefer:'resolution=merge-duplicates,return=minimal'});return send(res,200,await state(u))}
 return send(res,400,{error:'Unknown rewards action'})}catch(e){return send(res,e.status&&e.status<600?e.status:500,{error:e.message||'Rewards request failed'})}}
