import crypto from 'node:crypto';
import {requireUser,requireSameOrigin} from '../_auth.js';
import {db,enc} from '../_db.js';
import {newOnlineState,publicState,timeoutAction} from '../_online-engine.js';
import {broadcastRoom} from '../_realtime.js';
import {validRoomCode,roomExpired,canJoin,nextHost} from '../_room-policy.js';
import {recordCompletedMatch} from '../_match-results.js';
const send=(res,status,data)=>res.status(status).json(data);
const code=()=>{const a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return Array.from({length:6},()=>a[crypto.randomInt(0,a.length)]).join('')};
const colorFor=(seat,max)=>seat===0?'red':seat===1?(max===2?'yellow':'green'):seat===2?'yellow':'blue';
async function profile(user){const a=await db('online_profiles?user_id=eq.'+enc(user.id)+'&select=user_id,username,display_name,avatar&limit=1'),x=a?.[0],p={id:user.id,username:user.username,display_name:x?.display_name||user.display_name||user.username,avatar:x?.avatar||'avatar-1'};await db('online_profiles?on_conflict=user_id',{method:'POST',body:{user_id:user.id,username:p.username,display_name:p.display_name,avatar:p.avatar,last_seen:new Date().toISOString()},prefer:'resolution=merge-duplicates,return=representation'});return p}
async function roomByCode(c){const a=await db('online_rooms?code=eq.'+enc(c)+'&select=*&limit=1'),r=a&&a[0];if(roomExpired(r))return null;return r}
async function roomById(id){const a=await db('online_rooms?id=eq.'+enc(id)+'&select=*&limit=1');return a&&a[0]}
async function memberList(id){return await db('online_members?room_id=eq.'+enc(id)+'&select=*&order=seat.asc')||[]}
async function enforceTimer(r){const due=Date.parse(r?.state?.meta?.deadlineAt||0);if(!r||r.status!=='playing'||!r.state||!Number.isFinite(due)||Date.now()<due)return r;const state=timeoutAction(r.state),version=(r.version||0)+1,status=state.game.winner?'finished':'playing';const out=await db('online_rooms?id=eq.'+enc(r.id)+'&version=eq.'+enc(r.version),{method:'PATCH',body:{state,version,status,updated_at:new Date().toISOString()}});if(out?.[0]&&status==='finished')await recordCompletedMatch(out[0],await memberList(r.id));return out&&out[0]||await roomById(r.id)}
async function payload(r,user){if(!r)return{room:null,members:[]};r=await enforceTimer(r);let ms=await memberList(r.id);if(!ms.some(m=>m.user_id===user.id))throw Object.assign(new Error('You are not in this room'),{status:403});await db('online_members?room_id=eq.'+enc(r.id)+'&user_id=eq.'+enc(user.id),{method:'PATCH',body:{last_seen_at:new Date().toISOString()}});ms=await memberList(r.id);const me=ms.find(m=>m.user_id===user.id);return{room:{...r,state:r.state?publicState(r.state,me&&me.color):r.state},members:ms}}
export default async function handler(req,res){try{const user=await requireUser(req);if(req.method==='GET'){if(req.query.mine==='1'){const ms=await db('online_members?user_id=eq.'+enc(user.id)+'&select=room_id,joined_at&order=joined_at.desc&limit=8')||[];for(const m of ms){const r=await roomById(m.room_id);if(r&&r.status!=='finished')return send(res,200,await payload(r,user))}return send(res,200,{room:null,members:[]})}const c=String(req.query.code||'').toUpperCase();const r=await roomByCode(c);if(!r)return send(res,404,{error:'Room not found'});return send(res,200,await payload(r,user))}
 if(req.method!=='POST')return send(res,405,{error:'Method not allowed'});requireSameOrigin(req);const body=req.body||{},action=body.action;
 if(action==='create'){const p=await profile(user),max=[2,3,4].includes(+body.players)?+body.players:2,variant=['classic','color-cards'].includes(body.variant)?body.variant:'classic';let r=null;for(let i=0;i<6&&!r;i++){try{const out=await db('online_rooms',{method:'POST',body:{code:code(),host_id:user.id,status:'waiting',max_players:max,variant,options:{mode:body.mode==='500'?'500':'round',rules:variant==='classic'?'classic-v1':'color-cards-v1'},state:null,version:0,expires_at:new Date(Date.now()+(Number(process.env.ONLINE_ROOM_HOURS)||24)*3600000).toISOString()}});r=out&&out[0]}catch(e){if(e.status!==409)throw e}}if(!r)throw new Error('Could not create room');await db('online_members',{method:'POST',body:{room_id:r.id,user_id:user.id,seat:0,color:'red',ready:true,username:p.username,display_name:p.display_name,avatar:p.avatar}});return send(res,200,await payload(r,user))}
 const c=String(body.code||'').trim().toUpperCase();if(!validRoomCode(c))return send(res,400,{error:'Invalid room code'});let r=await roomByCode(c);if(!r)return send(res,404,{error:'Room not found'});
 if(action==='join'){const old=await memberList(r.id),check=canJoin(r,old,user.id);if(!check.ok)return send(res,check.error.includes('full')?409:404,{error:check.error});const existing=old.find(m=>m.user_id===user.id);if(existing)return send(res,200,await payload(r,user));const p=await profile(user),used=new Set(old.map(m=>m.seat));let seat=0;while(used.has(seat)&&seat<4)seat++;await db('online_members',{method:'POST',body:{room_id:r.id,user_id:user.id,seat,color:colorFor(seat,r.max_players),ready:false,username:p.username,display_name:p.display_name,avatar:p.avatar}});await broadcastRoom(r.id,'room_changed',{reason:'joined'});return send(res,200,await payload(r,user))}
 const ms=await memberList(r.id),me=ms.find(m=>m.user_id===user.id);if(!me)return send(res,403,{error:'You are not in this room'});
 if(action==='configure'){if(r.host_id!==user.id)return send(res,403,{error:'Only the host can change room settings'});if(r.status!=='waiting')return send(res,409,{error:'Rules are locked after the match starts'});const variant=['classic','color-cards'].includes(body.variant)?body.variant:r.variant,mode=body.mode==='500'?'500':'round';const out=await db('online_rooms?id=eq.'+enc(r.id)+'&status=eq.waiting',{method:'PATCH',body:{variant,options:{mode,rules:variant==='classic'?'classic-v1':'color-cards-v1'},updated_at:new Date().toISOString()}});await broadcastRoom(r.id,'room_changed',{reason:'configured'});return send(res,200,await payload(out?.[0]||await roomById(r.id),user))}
 if(action==='presence'){await db('online_members?room_id=eq.'+enc(r.id)+'&user_id=eq.'+enc(user.id),{method:'PATCH',body:{last_seen_at:new Date().toISOString()}});return send(res,200,{ok:true})}
 if(action==='ready'){if(r.status!=='waiting')return send(res,409,{error:'Match already started'});await db('online_members?room_id=eq.'+enc(r.id)+'&user_id=eq.'+enc(user.id),{method:'PATCH',body:{ready:!!body.ready}});await broadcastRoom(r.id,'room_changed',{reason:'ready'});return send(res,200,await payload(await roomById(r.id),user))}
 if(action==='start'){if(r.host_id!==user.id)return send(res,403,{error:'Only the host can start'});if(r.status!=='waiting')return send(res,409,{error:'Match already started'});if(ms.length!==r.max_players)return send(res,409,{error:'Waiting for all '+r.max_players+' players'});if(ms.some(m=>!m.ready))return send(res,409,{error:'Everyone must be ready'});const st=newOnlineState(ms.length,r.variant,r.options?.mode||'round');st.game.onlineRoom=r.id;const out=await db('online_rooms?id=eq.'+enc(r.id)+'&status=eq.waiting',{method:'PATCH',body:{status:'playing',state:st,version:(r.version||0)+1,updated_at:new Date().toISOString()}});if(!out||!out.length)return send(res,409,{error:'Room changed. Try again.'});await broadcastRoom(r.id,'room_changed',{reason:'started',version:out[0].version});return send(res,200,await payload(out[0],user))}
 if(action==='leave'){if(r.status==='playing')return send(res,409,{error:'Match is live. You can exit and rejoin from this account.'});await db('online_members?room_id=eq.'+enc(r.id)+'&user_id=eq.'+enc(user.id),{method:'DELETE'});const left=(await memberList(r.id));if(!left.length)await db('online_rooms?id=eq.'+enc(r.id),{method:'DELETE'});else if(r.host_id===user.id)await db('online_rooms?id=eq.'+enc(r.id),{method:'PATCH',body:{host_id:nextHost(left)}});await broadcastRoom(r.id,'room_changed',{reason:'left'});return send(res,200,{ok:true})}
 return send(res,400,{error:'Unknown room action'})
 }catch(e){return send(res,e.status&&e.status<600?e.status:500,{error:e.message||'Online room error'})}}
